package fintech.lending.creditline;

public class TransactionConstants {

    public static final String TRANSACTION_POSITION_PRINCIPAL = "PRINCIPAL";
    public static final String TRANSACTION_POSITION_INTEREST = "INTEREST";
    public static final String TRANSACTION_POSITION_PENALTY = "PENALTY";
    public static final String TRANSACTION_POSITION_FEE = "FEE";

    public static final String TRANSACTION_SUB_TYPE_UNIDENTIFIED_LIABILITIES_TO_CUSTOMERS = "UNIDENTIFIED_LIABILITIES_TO_CUSTOMERS";
    public static final String TRANSACTION_SUB_TYPE_FAULTY_OUT = "FAULTY_OUT";
    public static final String TRANSACTION_SUB_TYPE_BANK_COMMISSION = "BANK_COMMISSION";
    public static final String TRANSACTION_SUB_TYPE_INTER_COMPANY_TRANSFER = "INTER_COMPANY_TRANSFER";
    public static final String TRANSACTION_SUB_TYPE_OTHER = "OTHER";
    public static final String TRANSACTION_SUB_TYPE_PRINCIPAL_VIVENTOR = "PRINCIPAL_VIVENTOR";
    public static final String TRANSACTION_SUB_TYPE_PREPAYMENT = "PREPAYMENT";
    public static final String TRANSACTION_SUB_TYPE_INSTALLMENT_REPAYMENT = "INSTALLMENT_REPAYMENT";
    public static final String TRANSACTION_SUB_TYPE_RESCHEDULE_REPAYMENT = "RESCHEDULE_REPAYMENT";

    public static final String TRANSACTION_SUB_TYPE_FIRST_DISBURSEMENT_FEE = "FIRST_DISBURSEMENT_FEE";
    public static final String TRANSACTION_SUB_TYPE_REPEATED_DISBURSEMENT_FEE = "REPEATED_DISBURSEMENT_FEE";

    public static final String TRANSACTION_SUB_TYPE_RESCHEDULING_FEE = "RESCHEDULING_FEE";

}
