/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.quartz;


import fintech.bo.db.jooq.quartz.tables.*;
import fintech.bo.db.jooq.quartz.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>quartz</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<QrtzBlobTriggersRecord> QRTZ_BLOB_TRIGGERS_PKEY = UniqueKeys0.QRTZ_BLOB_TRIGGERS_PKEY;
    public static final UniqueKey<QrtzCalendarsRecord> QRTZ_CALENDARS_PKEY = UniqueKeys0.QRTZ_CALENDARS_PKEY;
    public static final UniqueKey<QrtzCronTriggersRecord> QRTZ_CRON_TRIGGERS_PKEY = UniqueKeys0.QRTZ_CRON_TRIGGERS_PKEY;
    public static final UniqueKey<QrtzFiredTriggersRecord> QRTZ_FIRED_TRIGGERS_PKEY = UniqueKeys0.QRTZ_FIRED_TRIGGERS_PKEY;
    public static final UniqueKey<QrtzJobDetailsRecord> QRTZ_JOB_DETAILS_PKEY = UniqueKeys0.QRTZ_JOB_DETAILS_PKEY;
    public static final UniqueKey<QrtzLocksRecord> QRTZ_LOCKS_PKEY = UniqueKeys0.QRTZ_LOCKS_PKEY;
    public static final UniqueKey<QrtzPausedTriggerGrpsRecord> QRTZ_PAUSED_TRIGGER_GRPS_PKEY = UniqueKeys0.QRTZ_PAUSED_TRIGGER_GRPS_PKEY;
    public static final UniqueKey<QrtzSchedulerStateRecord> QRTZ_SCHEDULER_STATE_PKEY = UniqueKeys0.QRTZ_SCHEDULER_STATE_PKEY;
    public static final UniqueKey<QrtzSimpleTriggersRecord> QRTZ_SIMPLE_TRIGGERS_PKEY = UniqueKeys0.QRTZ_SIMPLE_TRIGGERS_PKEY;
    public static final UniqueKey<QrtzSimpropTriggersRecord> QRTZ_SIMPROP_TRIGGERS_PKEY = UniqueKeys0.QRTZ_SIMPROP_TRIGGERS_PKEY;
    public static final UniqueKey<QrtzTriggersRecord> QRTZ_TRIGGERS_PKEY = UniqueKeys0.QRTZ_TRIGGERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<QrtzBlobTriggersRecord, QrtzTriggersRecord> QRTZ_BLOB_TRIGGERS__QRTZ_BLOB_TRIGGERS_SCHED_NAME_FKEY = ForeignKeys0.QRTZ_BLOB_TRIGGERS__QRTZ_BLOB_TRIGGERS_SCHED_NAME_FKEY;
    public static final ForeignKey<QrtzCronTriggersRecord, QrtzTriggersRecord> QRTZ_CRON_TRIGGERS__QRTZ_CRON_TRIGGERS_SCHED_NAME_FKEY = ForeignKeys0.QRTZ_CRON_TRIGGERS__QRTZ_CRON_TRIGGERS_SCHED_NAME_FKEY;
    public static final ForeignKey<QrtzSimpleTriggersRecord, QrtzTriggersRecord> QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_FKEY = ForeignKeys0.QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_FKEY;
    public static final ForeignKey<QrtzSimpropTriggersRecord, QrtzTriggersRecord> QRTZ_SIMPROP_TRIGGERS__QRTZ_SIMPROP_TRIGGERS_SCHED_NAME_FKEY = ForeignKeys0.QRTZ_SIMPROP_TRIGGERS__QRTZ_SIMPROP_TRIGGERS_SCHED_NAME_FKEY;
    public static final ForeignKey<QrtzTriggersRecord, QrtzJobDetailsRecord> QRTZ_TRIGGERS__QRTZ_TRIGGERS_SCHED_NAME_FKEY = ForeignKeys0.QRTZ_TRIGGERS__QRTZ_TRIGGERS_SCHED_NAME_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<QrtzBlobTriggersRecord> QRTZ_BLOB_TRIGGERS_PKEY = createUniqueKey(QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS, "qrtz_blob_triggers_pkey", QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.SCHED_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP);
        public static final UniqueKey<QrtzCalendarsRecord> QRTZ_CALENDARS_PKEY = createUniqueKey(QrtzCalendars.QRTZ_CALENDARS, "qrtz_calendars_pkey", QrtzCalendars.QRTZ_CALENDARS.SCHED_NAME, QrtzCalendars.QRTZ_CALENDARS.CALENDAR_NAME);
        public static final UniqueKey<QrtzCronTriggersRecord> QRTZ_CRON_TRIGGERS_PKEY = createUniqueKey(QrtzCronTriggers.QRTZ_CRON_TRIGGERS, "qrtz_cron_triggers_pkey", QrtzCronTriggers.QRTZ_CRON_TRIGGERS.SCHED_NAME, QrtzCronTriggers.QRTZ_CRON_TRIGGERS.TRIGGER_NAME, QrtzCronTriggers.QRTZ_CRON_TRIGGERS.TRIGGER_GROUP);
        public static final UniqueKey<QrtzFiredTriggersRecord> QRTZ_FIRED_TRIGGERS_PKEY = createUniqueKey(QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, "qrtz_fired_triggers_pkey", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.ENTRY_ID);
        public static final UniqueKey<QrtzJobDetailsRecord> QRTZ_JOB_DETAILS_PKEY = createUniqueKey(QrtzJobDetails.QRTZ_JOB_DETAILS, "qrtz_job_details_pkey", QrtzJobDetails.QRTZ_JOB_DETAILS.SCHED_NAME, QrtzJobDetails.QRTZ_JOB_DETAILS.JOB_NAME, QrtzJobDetails.QRTZ_JOB_DETAILS.JOB_GROUP);
        public static final UniqueKey<QrtzLocksRecord> QRTZ_LOCKS_PKEY = createUniqueKey(QrtzLocks.QRTZ_LOCKS, "qrtz_locks_pkey", QrtzLocks.QRTZ_LOCKS.SCHED_NAME, QrtzLocks.QRTZ_LOCKS.LOCK_NAME);
        public static final UniqueKey<QrtzPausedTriggerGrpsRecord> QRTZ_PAUSED_TRIGGER_GRPS_PKEY = createUniqueKey(QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS, "qrtz_paused_trigger_grps_pkey", QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME, QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP);
        public static final UniqueKey<QrtzSchedulerStateRecord> QRTZ_SCHEDULER_STATE_PKEY = createUniqueKey(QrtzSchedulerState.QRTZ_SCHEDULER_STATE, "qrtz_scheduler_state_pkey", QrtzSchedulerState.QRTZ_SCHEDULER_STATE.SCHED_NAME, QrtzSchedulerState.QRTZ_SCHEDULER_STATE.INSTANCE_NAME);
        public static final UniqueKey<QrtzSimpleTriggersRecord> QRTZ_SIMPLE_TRIGGERS_PKEY = createUniqueKey(QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS, "qrtz_simple_triggers_pkey", QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.SCHED_NAME, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP);
        public static final UniqueKey<QrtzSimpropTriggersRecord> QRTZ_SIMPROP_TRIGGERS_PKEY = createUniqueKey(QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS, "qrtz_simprop_triggers_pkey", QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP);
        public static final UniqueKey<QrtzTriggersRecord> QRTZ_TRIGGERS_PKEY = createUniqueKey(QrtzTriggers.QRTZ_TRIGGERS, "qrtz_triggers_pkey", QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_GROUP);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<QrtzBlobTriggersRecord, QrtzTriggersRecord> QRTZ_BLOB_TRIGGERS__QRTZ_BLOB_TRIGGERS_SCHED_NAME_FKEY = createForeignKey(fintech.bo.db.jooq.quartz.Keys.QRTZ_TRIGGERS_PKEY, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS, "qrtz_blob_triggers__qrtz_blob_triggers_sched_name_fkey", QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.SCHED_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP);
        public static final ForeignKey<QrtzCronTriggersRecord, QrtzTriggersRecord> QRTZ_CRON_TRIGGERS__QRTZ_CRON_TRIGGERS_SCHED_NAME_FKEY = createForeignKey(fintech.bo.db.jooq.quartz.Keys.QRTZ_TRIGGERS_PKEY, QrtzCronTriggers.QRTZ_CRON_TRIGGERS, "qrtz_cron_triggers__qrtz_cron_triggers_sched_name_fkey", QrtzCronTriggers.QRTZ_CRON_TRIGGERS.SCHED_NAME, QrtzCronTriggers.QRTZ_CRON_TRIGGERS.TRIGGER_NAME, QrtzCronTriggers.QRTZ_CRON_TRIGGERS.TRIGGER_GROUP);
        public static final ForeignKey<QrtzSimpleTriggersRecord, QrtzTriggersRecord> QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_FKEY = createForeignKey(fintech.bo.db.jooq.quartz.Keys.QRTZ_TRIGGERS_PKEY, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS, "qrtz_simple_triggers__qrtz_simple_triggers_sched_name_fkey", QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.SCHED_NAME, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP);
        public static final ForeignKey<QrtzSimpropTriggersRecord, QrtzTriggersRecord> QRTZ_SIMPROP_TRIGGERS__QRTZ_SIMPROP_TRIGGERS_SCHED_NAME_FKEY = createForeignKey(fintech.bo.db.jooq.quartz.Keys.QRTZ_TRIGGERS_PKEY, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS, "qrtz_simprop_triggers__qrtz_simprop_triggers_sched_name_fkey", QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP);
        public static final ForeignKey<QrtzTriggersRecord, QrtzJobDetailsRecord> QRTZ_TRIGGERS__QRTZ_TRIGGERS_SCHED_NAME_FKEY = createForeignKey(fintech.bo.db.jooq.quartz.Keys.QRTZ_JOB_DETAILS_PKEY, QrtzTriggers.QRTZ_TRIGGERS, "qrtz_triggers__qrtz_triggers_sched_name_fkey", QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.JOB_NAME, QrtzTriggers.QRTZ_TRIGGERS.JOB_GROUP);
    }
}
