/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.quartz;


import fintech.bo.db.jooq.quartz.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in quartz
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>quartz.qrtz_blob_triggers</code>.
     */
    public static final QrtzBlobTriggers QRTZ_BLOB_TRIGGERS = fintech.bo.db.jooq.quartz.tables.QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS;

    /**
     * The table <code>quartz.qrtz_calendars</code>.
     */
    public static final QrtzCalendars QRTZ_CALENDARS = fintech.bo.db.jooq.quartz.tables.QrtzCalendars.QRTZ_CALENDARS;

    /**
     * The table <code>quartz.qrtz_cron_triggers</code>.
     */
    public static final QrtzCronTriggers QRTZ_CRON_TRIGGERS = fintech.bo.db.jooq.quartz.tables.QrtzCronTriggers.QRTZ_CRON_TRIGGERS;

    /**
     * The table <code>quartz.qrtz_fired_triggers</code>.
     */
    public static final QrtzFiredTriggers QRTZ_FIRED_TRIGGERS = fintech.bo.db.jooq.quartz.tables.QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS;

    /**
     * The table <code>quartz.qrtz_job_details</code>.
     */
    public static final QrtzJobDetails QRTZ_JOB_DETAILS = fintech.bo.db.jooq.quartz.tables.QrtzJobDetails.QRTZ_JOB_DETAILS;

    /**
     * The table <code>quartz.qrtz_locks</code>.
     */
    public static final QrtzLocks QRTZ_LOCKS = fintech.bo.db.jooq.quartz.tables.QrtzLocks.QRTZ_LOCKS;

    /**
     * The table <code>quartz.qrtz_paused_trigger_grps</code>.
     */
    public static final QrtzPausedTriggerGrps QRTZ_PAUSED_TRIGGER_GRPS = fintech.bo.db.jooq.quartz.tables.QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS;

    /**
     * The table <code>quartz.qrtz_scheduler_state</code>.
     */
    public static final QrtzSchedulerState QRTZ_SCHEDULER_STATE = fintech.bo.db.jooq.quartz.tables.QrtzSchedulerState.QRTZ_SCHEDULER_STATE;

    /**
     * The table <code>quartz.qrtz_simple_triggers</code>.
     */
    public static final QrtzSimpleTriggers QRTZ_SIMPLE_TRIGGERS = fintech.bo.db.jooq.quartz.tables.QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS;

    /**
     * The table <code>quartz.qrtz_simprop_triggers</code>.
     */
    public static final QrtzSimpropTriggers QRTZ_SIMPROP_TRIGGERS = fintech.bo.db.jooq.quartz.tables.QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS;

    /**
     * The table <code>quartz.qrtz_triggers</code>.
     */
    public static final QrtzTriggers QRTZ_TRIGGERS = fintech.bo.db.jooq.quartz.tables.QrtzTriggers.QRTZ_TRIGGERS;
}
