/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.workflow.tables.records;


import fintech.bo.db.jooq.workflow.tables.Activity;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityRecord extends UpdatableRecordImpl<ActivityRecord> implements Record18<Long, LocalDateTime, String, Long, LocalDateTime, String, String, Long, LocalDateTime, String, LocalDateTime, String, LocalDateTime, String, String, String, Long, String> {

    private static final long serialVersionUID = 1022707431;

    /**
     * Setter for <code>workflow.activity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.activity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow.activity.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.activity.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>workflow.activity.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.activity.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.activity.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.activity.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>workflow.activity.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.activity.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>workflow.activity.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.activity.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow.activity.actor</code>.
     */
    public void setActor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.activity.actor</code>.
     */
    public String getActor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.activity.attempts</code>.
     */
    public void setAttempts(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.activity.attempts</code>.
     */
    public Long getAttempts() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>workflow.activity.completed_at</code>.
     */
    public void setCompletedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.activity.completed_at</code>.
     */
    public LocalDateTime getCompletedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>workflow.activity.error</code>.
     */
    public void setError(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.activity.error</code>.
     */
    public String getError() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.activity.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.activity.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>workflow.activity.name</code>.
     */
    public void setName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.activity.name</code>.
     */
    public String getName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow.activity.next_attempt_at</code>.
     */
    public void setNextAttemptAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.activity.next_attempt_at</code>.
     */
    public LocalDateTime getNextAttemptAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>workflow.activity.resolution</code>.
     */
    public void setResolution(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.activity.resolution</code>.
     */
    public String getResolution() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow.activity.resolution_detail</code>.
     */
    public void setResolutionDetail(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow.activity.resolution_detail</code>.
     */
    public String getResolutionDetail() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow.activity.status</code>.
     */
    public void setStatus(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow.activity.status</code>.
     */
    public String getStatus() {
        return (String) get(15);
    }

    /**
     * Setter for <code>workflow.activity.workflow_id</code>.
     */
    public void setWorkflowId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow.activity.workflow_id</code>.
     */
    public Long getWorkflowId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>workflow.activity.ui_state</code>.
     */
    public void setUiState(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>workflow.activity.ui_state</code>.
     */
    public String getUiState() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, LocalDateTime, String, Long, LocalDateTime, String, String, Long, LocalDateTime, String, LocalDateTime, String, LocalDateTime, String, String, String, Long, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, LocalDateTime, String, Long, LocalDateTime, String, String, Long, LocalDateTime, String, LocalDateTime, String, LocalDateTime, String, String, String, Long, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Activity.ACTIVITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return Activity.ACTIVITY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Activity.ACTIVITY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Activity.ACTIVITY.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return Activity.ACTIVITY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Activity.ACTIVITY.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Activity.ACTIVITY.ACTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Activity.ACTIVITY.ATTEMPTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return Activity.ACTIVITY.COMPLETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Activity.ACTIVITY.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return Activity.ACTIVITY.EXPIRES_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Activity.ACTIVITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return Activity.ACTIVITY.NEXT_ATTEMPT_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Activity.ACTIVITY.RESOLUTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Activity.ACTIVITY.RESOLUTION_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Activity.ACTIVITY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Activity.ACTIVITY.WORKFLOW_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Activity.ACTIVITY.UI_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getActor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getAttempts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCompletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getNextAttemptAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getResolution();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getResolutionDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getWorkflowId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getUiState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value7(String value) {
        setActor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value8(Long value) {
        setAttempts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value9(LocalDateTime value) {
        setCompletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value10(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value11(LocalDateTime value) {
        setExpiresAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value12(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value13(LocalDateTime value) {
        setNextAttemptAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value14(String value) {
        setResolution(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value15(String value) {
        setResolutionDetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value16(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value17(Long value) {
        setWorkflowId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value18(String value) {
        setUiState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, String value7, Long value8, LocalDateTime value9, String value10, LocalDateTime value11, String value12, LocalDateTime value13, String value14, String value15, String value16, Long value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, String actor, Long attempts, LocalDateTime completedAt, String error, LocalDateTime expiresAt, String name, LocalDateTime nextAttemptAt, String resolution, String resolutionDetail, String status, Long workflowId, String uiState) {
        super(Activity.ACTIVITY);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, actor);
        set(7, attempts);
        set(8, completedAt);
        set(9, error);
        set(10, expiresAt);
        set(11, name);
        set(12, nextAttemptAt);
        set(13, resolution);
        set(14, resolutionDetail);
        set(15, status);
        set(16, workflowId);
        set(17, uiState);
    }
}
