/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.affiliate.tables.records;


import fintech.bo.db.jooq.affiliate.tables.Event;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record18<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, Long, String, Long, LocalDateTime, String, Integer, String, String, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = -885632094;

    /**
     * Setter for <code>affiliate.event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>affiliate.event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>affiliate.event.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>affiliate.event.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>affiliate.event.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>affiliate.event.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>affiliate.event.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>affiliate.event.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>affiliate.event.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>affiliate.event.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>affiliate.event.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>affiliate.event.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>affiliate.event.application_id</code>.
     */
    public void setApplicationId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>affiliate.event.application_id</code>.
     */
    public Long getApplicationId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>affiliate.event.client_id</code>.
     */
    public void setClientId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>affiliate.event.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>affiliate.event.event_type</code>.
     */
    public void setEventType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>affiliate.event.event_type</code>.
     */
    public String getEventType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>affiliate.event.loan_id</code>.
     */
    public void setLoanId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>affiliate.event.loan_id</code>.
     */
    public Long getLoanId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>affiliate.event.next_report_attempt_at</code>.
     */
    public void setNextReportAttemptAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>affiliate.event.next_report_attempt_at</code>.
     */
    public LocalDateTime getNextReportAttemptAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>affiliate.event.report_error</code>.
     */
    public void setReportError(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>affiliate.event.report_error</code>.
     */
    public String getReportError() {
        return (String) get(11);
    }

    /**
     * Setter for <code>affiliate.event.report_retry_attempts</code>.
     */
    public void setReportRetryAttempts(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>affiliate.event.report_retry_attempts</code>.
     */
    public Integer getReportRetryAttempts() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>affiliate.event.report_status</code>.
     */
    public void setReportStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>affiliate.event.report_status</code>.
     */
    public String getReportStatus() {
        return (String) get(13);
    }

    /**
     * Setter for <code>affiliate.event.report_url</code>.
     */
    public void setReportUrl(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>affiliate.event.report_url</code>.
     */
    public String getReportUrl() {
        return (String) get(14);
    }

    /**
     * Setter for <code>affiliate.event.reported_at</code>.
     */
    public void setReportedAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>affiliate.event.reported_at</code>.
     */
    public LocalDateTime getReportedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>affiliate.event.lead_id</code>.
     */
    public void setLeadId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>affiliate.event.lead_id</code>.
     */
    public Long getLeadId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>affiliate.event.partner_id</code>.
     */
    public void setPartnerId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>affiliate.event.partner_id</code>.
     */
    public Long getPartnerId() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, Long, String, Long, LocalDateTime, String, Integer, String, String, LocalDateTime, Long, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, Long, String, Long, LocalDateTime, String, Integer, String, String, LocalDateTime, Long, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Event.EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return Event.EVENT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Event.EVENT.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Event.EVENT.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return Event.EVENT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Event.EVENT.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Event.EVENT.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Event.EVENT.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Event.EVENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Event.EVENT.LOAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return Event.EVENT.NEXT_REPORT_ATTEMPT_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Event.EVENT.REPORT_ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Event.EVENT.REPORT_RETRY_ATTEMPTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Event.EVENT.REPORT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Event.EVENT.REPORT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return Event.EVENT.REPORTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Event.EVENT.LEAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return Event.EVENT.PARTNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getNextReportAttemptAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getReportError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getReportRetryAttempts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getReportStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getReportUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getReportedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getLeadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value7(Long value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value8(Long value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value9(String value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value10(Long value) {
        setLoanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value11(LocalDateTime value) {
        setNextReportAttemptAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value12(String value) {
        setReportError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value13(Integer value) {
        setReportRetryAttempts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value14(String value) {
        setReportStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value15(String value) {
        setReportUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value16(LocalDateTime value) {
        setReportedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value17(Long value) {
        setLeadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value18(Long value) {
        setPartnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, Long value7, Long value8, String value9, Long value10, LocalDateTime value11, String value12, Integer value13, String value14, String value15, LocalDateTime value16, Long value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, Long applicationId, Long clientId, String eventType, Long loanId, LocalDateTime nextReportAttemptAt, String reportError, Integer reportRetryAttempts, String reportStatus, String reportUrl, LocalDateTime reportedAt, Long leadId, Long partnerId) {
        super(Event.EVENT);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, applicationId);
        set(7, clientId);
        set(8, eventType);
        set(9, loanId);
        set(10, nextReportAttemptAt);
        set(11, reportError);
        set(12, reportRetryAttempts);
        set(13, reportStatus);
        set(14, reportUrl);
        set(15, reportedAt);
        set(16, leadId);
        set(17, partnerId);
    }
}
