/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.dc.tables;


import fintech.bo.db.jooq.dc.Dc;
import fintech.bo.db.jooq.dc.Keys;
import fintech.bo.db.jooq.dc.tables.records.AgentPortfolioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgentPortfolio extends TableImpl<AgentPortfolioRecord> {

    private static final long serialVersionUID = -1602640162;

    /**
     * The reference instance of <code>dc.agent_portfolio</code>
     */
    public static final AgentPortfolio AGENT_PORTFOLIO = new AgentPortfolio();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentPortfolioRecord> getRecordType() {
        return AgentPortfolioRecord.class;
    }

    /**
     * The column <code>dc.agent_portfolio.agent_id</code>.
     */
    public final TableField<AgentPortfolioRecord, Long> AGENT_ID = createField("agent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>dc.agent_portfolio.portfolios</code>.
     */
    public final TableField<AgentPortfolioRecord, String> PORTFOLIOS = createField("portfolios", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>dc.agent_portfolio</code> table reference
     */
    public AgentPortfolio() {
        this("agent_portfolio", null);
    }

    /**
     * Create an aliased <code>dc.agent_portfolio</code> table reference
     */
    public AgentPortfolio(String alias) {
        this(alias, AGENT_PORTFOLIO);
    }

    private AgentPortfolio(String alias, Table<AgentPortfolioRecord> aliased) {
        this(alias, aliased, null);
    }

    private AgentPortfolio(String alias, Table<AgentPortfolioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dc.DC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AgentPortfolioRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AgentPortfolioRecord, ?>>asList(Keys.AGENT_PORTFOLIO__FK8C04TA12JLS514T7PFFYE9SDE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgentPortfolio as(String alias) {
        return new AgentPortfolio(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentPortfolio rename(String name) {
        return new AgentPortfolio(name, null);
    }
}
