/*
 * This file is generated by jOOQ.
*/
package fintech.bo.spain.alfa.db.jooq.alfa.tables.records;


import fintech.bo.spain.alfa.db.jooq.alfa.tables.AlfaMonthlyInterestStrategy;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlfaMonthlyInterestStrategyRecord extends UpdatableRecordImpl<AlfaMonthlyInterestStrategyRecord> implements Record10<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, BigDecimal, Boolean, String> {

    private static final long serialVersionUID = 839994548;

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.calculation_strategy_id</code>.
     */
    public void setCalculationStrategyId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.calculation_strategy_id</code>.
     */
    public Long getCalculationStrategyId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.interest_rate</code>.
     */
    public void setInterestRate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.interest_rate</code>.
     */
    public BigDecimal getInterestRate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.using_decision_engine</code>.
     */
    public void setUsingDecisionEngine(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.using_decision_engine</code>.
     */
    public Boolean getUsingDecisionEngine() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>alfa.alfa_monthly_interest_strategy.scenario</code>.
     */
    public void setScenario(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>alfa.alfa_monthly_interest_strategy.scenario</code>.
     */
    public String getScenario() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, BigDecimal, Boolean, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, BigDecimal, Boolean, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.CALCULATION_STRATEGY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.INTEREST_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.USING_DECISION_ENGINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY.SCENARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCalculationStrategyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getInterestRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getUsingDecisionEngine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getScenario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value7(Long value) {
        setCalculationStrategyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value8(BigDecimal value) {
        setInterestRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value9(Boolean value) {
        setUsingDecisionEngine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord value10(String value) {
        setScenario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategyRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, Long value7, BigDecimal value8, Boolean value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlfaMonthlyInterestStrategyRecord
     */
    public AlfaMonthlyInterestStrategyRecord() {
        super(AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY);
    }

    /**
     * Create a detached, initialised AlfaMonthlyInterestStrategyRecord
     */
    public AlfaMonthlyInterestStrategyRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, Long calculationStrategyId, BigDecimal interestRate, Boolean usingDecisionEngine, String scenario) {
        super(AlfaMonthlyInterestStrategy.ALFA_MONTHLY_INTEREST_STRATEGY);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, calculationStrategyId);
        set(7, interestRate);
        set(8, usingDecisionEngine);
        set(9, scenario);
    }
}
