/*
 * This file is generated by jOOQ.
*/
package fintech.bo.spain.alfa.db.jooq.alfa.tables.records;


import fintech.bo.spain.alfa.db.jooq.alfa.tables.LoanRescheduling;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanReschedulingRecord extends UpdatableRecordImpl<LoanReschedulingRecord> implements Record14<Long, Long, String, Integer, Integer, Integer, BigDecimal, LocalDate, LocalDate, Long, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = -362981476;

    /**
     * Setter for <code>alfa.loan_rescheduling.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.loan_id</code>.
     */
    public void setLoanId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.loan_id</code>.
     */
    public Long getLoanId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.number_of_payments</code>.
     */
    public void setNumberOfPayments(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.number_of_payments</code>.
     */
    public Integer getNumberOfPayments() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.repayment_due_days</code>.
     */
    public void setRepaymentDueDays(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.repayment_due_days</code>.
     */
    public Integer getRepaymentDueDays() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.grace_period_days</code>.
     */
    public void setGracePeriodDays(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.grace_period_days</code>.
     */
    public Integer getGracePeriodDays() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.installment_amount</code>.
     */
    public void setInstallmentAmount(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.installment_amount</code>.
     */
    public BigDecimal getInstallmentAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.reschedule_date</code>.
     */
    public void setRescheduleDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.reschedule_date</code>.
     */
    public LocalDate getRescheduleDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.expire_date</code>.
     */
    public void setExpireDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.expire_date</code>.
     */
    public LocalDate getExpireDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>alfa.loan_rescheduling.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>alfa.loan_rescheduling.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, Integer, Integer, Integer, BigDecimal, LocalDate, LocalDate, Long, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, Integer, Integer, Integer, BigDecimal, LocalDate, LocalDate, Long, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LoanRescheduling.LOAN_RESCHEDULING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return LoanRescheduling.LOAN_RESCHEDULING.LOAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LoanRescheduling.LOAN_RESCHEDULING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return LoanRescheduling.LOAN_RESCHEDULING.NUMBER_OF_PAYMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return LoanRescheduling.LOAN_RESCHEDULING.REPAYMENT_DUE_DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return LoanRescheduling.LOAN_RESCHEDULING.GRACE_PERIOD_DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return LoanRescheduling.LOAN_RESCHEDULING.INSTALLMENT_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field8() {
        return LoanRescheduling.LOAN_RESCHEDULING.RESCHEDULE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field9() {
        return LoanRescheduling.LOAN_RESCHEDULING.EXPIRE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return LoanRescheduling.LOAN_RESCHEDULING.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return LoanRescheduling.LOAN_RESCHEDULING.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return LoanRescheduling.LOAN_RESCHEDULING.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return LoanRescheduling.LOAN_RESCHEDULING.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return LoanRescheduling.LOAN_RESCHEDULING.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNumberOfPayments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRepaymentDueDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGracePeriodDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getInstallmentAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value8() {
        return getRescheduleDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value9() {
        return getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value2(Long value) {
        setLoanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value4(Integer value) {
        setNumberOfPayments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value5(Integer value) {
        setRepaymentDueDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value6(Integer value) {
        setGracePeriodDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value7(BigDecimal value) {
        setInstallmentAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value8(LocalDate value) {
        setRescheduleDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value9(LocalDate value) {
        setExpireDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value10(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value11(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value12(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value13(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord value14(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanReschedulingRecord values(Long value1, Long value2, String value3, Integer value4, Integer value5, Integer value6, BigDecimal value7, LocalDate value8, LocalDate value9, Long value10, LocalDateTime value11, String value12, LocalDateTime value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanReschedulingRecord
     */
    public LoanReschedulingRecord() {
        super(LoanRescheduling.LOAN_RESCHEDULING);
    }

    /**
     * Create a detached, initialised LoanReschedulingRecord
     */
    public LoanReschedulingRecord(Long id, Long loanId, String status, Integer numberOfPayments, Integer repaymentDueDays, Integer gracePeriodDays, BigDecimal installmentAmount, LocalDate rescheduleDate, LocalDate expireDate, Long entityVersion, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(LoanRescheduling.LOAN_RESCHEDULING);

        set(0, id);
        set(1, loanId);
        set(2, status);
        set(3, numberOfPayments);
        set(4, repaymentDueDays);
        set(5, gracePeriodDays);
        set(6, installmentAmount);
        set(7, rescheduleDate);
        set(8, expireDate);
        set(9, entityVersion);
        set(10, createdAt);
        set(11, createdBy);
        set(12, updatedAt);
        set(13, updatedBy);
    }
}
