package fintech.spain.alfa.web.services.navigation;

public class UiState {
    public static final String REGISTRATION_PERSONAL_DATA = "REGISTRATION_PERSONAL_DATA";
    public static final String REGISTRATION_PHONE_VERIFICATION = "REGISTRATION_PHONE_VERIFICATION";
    public static final String REGISTRATION_INSTANTOR = "REGISTRATION_INSTANTOR";
    public static final String REGISTRATION_INSTANTOR_REVIEW = "REGISTRATION_INSTANTOR_REVIEW";
    public static final String REGISTRATION_APPROVE_LOAN_OFFER = "REGISTRATION_APPROVE_LOAN_OFFER";
    public static final String REGISTRATION_DNI_DOC_UPLOAD = "REGISTRATION_DNI_DOC_UPLOAD";
    public static final String REGISTRATION_DNI_DOC_VALIDATION = "REGISTRATION_DNI_DOC_VALIDATION";
    public static final String REGISTRATION_IOVATION_BLACK_BOX = "REGISTRATION_IOVATION_BLACK_BOX";
    public static final String REGISTRATION_PROCESSING = "REGISTRATION_PROCESSING";
    public static final String PROFILE = "PROFILE";
    public static final String REGISTRATION_MANUAL_TASK = "REGISTRATION_MANUAL_TASK";
    public static final String UNDERWRITING_IN_PROGRESS = "UNDERWRITING_IN_PROGRESS";
    public static final String CHANGE_BANK_ACCOUNT_VERIFY = "CHANGE_BANK_ACCOUNT_VERIFY";
    public static final String CHANGE_BANK_ACCOUNT_IN_PROGRESS = "CHANGE_BANK_ACCOUNT_IN_PROGRESS";
    public static final String CHANGE_BANK_ACCOUNT_CHOICE = "CHANGE_BANK_ACCOUNT_CHOICE";
    public static final String DORMANTS_WF_INSTANTOR_FORM = "DORMANTS_WF_INSTANTOR_FORM";
    public static final String DORMANTS_WF_IN_PROGRESS = "DORMANTS_WF_IN_PROGRESS";
    public static final String DORMANTS_WF_INSTANTOR_REVIEW = "DORMANTS_WF_INSTANTOR_REVIEW";
    public static final String DORMANTS_WF_MANUAL_CHECK = "DORMANTS_WF_MANUAL_CHECK";
    public static final String DORMANTS_WF_PHONE_VALIDATION = "DORMANTS_WF_PHONE_VALIDATION";
    public static final String DORMANTS_WF_LOAN_OFFER = "DORMANTS_WF_LOAN_OFFER";
    public static final String DORMANTS_WF_REDIRECT_TO_PRESTO = "DORMANTS_WF_REDIRECT_TO_PRESTO";
}
