/*
 * This file is generated by jOOQ.
*/
package fintech.bo.spain.db.jooq.inglobaly;


import fintech.bo.spain.db.jooq.inglobaly.tables.Response;
import fintech.bo.spain.db.jooq.inglobaly.tables.records.ResponseRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>spain_inglobaly</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ResponseRecord> RESPONSE_PKEY = UniqueKeys0.RESPONSE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ResponseRecord> RESPONSE_PKEY = createUniqueKey(Response.RESPONSE, "response_pkey", Response.RESPONSE.ID);
    }
}
