/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.decision_engine;


import fintech.bo.db.jooq.decision_engine.tables.Request;
import fintech.bo.db.jooq.decision_engine.tables.ScoringValueUsage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in decision_engine
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>decision_engine.request</code>.
     */
    public static final Request REQUEST = fintech.bo.db.jooq.decision_engine.tables.Request.REQUEST;

    /**
     * The table <code>decision_engine.scoring_value_usage</code>.
     */
    public static final ScoringValueUsage SCORING_VALUE_USAGE = fintech.bo.db.jooq.decision_engine.tables.ScoringValueUsage.SCORING_VALUE_USAGE;
}
