/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.admin_tools;


import fintech.bo.db.jooq.admin_tools.tables.Log;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in admin_tools
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>admin_tools.log</code>.
     */
    public static final Log LOG = fintech.bo.db.jooq.admin_tools.tables.Log.LOG;
}
