/*
 * This file is generated by jOOQ.
*/
package fintech.bo.spain.db.jooq.equifax.tables.records;


import fintech.bo.spain.db.jooq.equifax.tables.Equifax;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquifaxRecord extends UpdatableRecordImpl<EquifaxRecord> {

    private static final long serialVersionUID = 1434341775;

    /**
     * Setter for <code>spain_equifax.equifax.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>spain_equifax.equifax.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>spain_equifax.equifax.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spain_equifax.equifax.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>spain_equifax.equifax.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>spain_equifax.equifax.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spain_equifax.equifax.application_id</code>.
     */
    public void setApplicationId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.application_id</code>.
     */
    public Long getApplicationId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>spain_equifax.equifax.client_id</code>.
     */
    public void setClientId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>spain_equifax.equifax.delincuency_days</code>.
     */
    public void setDelincuencyDays(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.delincuency_days</code>.
     */
    public Long getDelincuencyDays() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>spain_equifax.equifax.document_number</code>.
     */
    public void setDocumentNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.document_number</code>.
     */
    public String getDocumentNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>spain_equifax.equifax.error</code>.
     */
    public void setError(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.error</code>.
     */
    public String getError() {
        return (String) get(10);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_consumer_credit_operations</code>.
     */
    public void setNumberOfConsumerCreditOperations(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_consumer_credit_operations</code>.
     */
    public Long getNumberOfConsumerCreditOperations() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_credit_card_operations</code>.
     */
    public void setNumberOfCreditCardOperations(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_credit_card_operations</code>.
     */
    public Long getNumberOfCreditCardOperations() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_creditors</code>.
     */
    public void setNumberOfCreditors(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_creditors</code>.
     */
    public Long getNumberOfCreditors() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_days_of_worst_situation</code>.
     */
    public void setNumberOfDaysOfWorstSituation(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_days_of_worst_situation</code>.
     */
    public Long getNumberOfDaysOfWorstSituation() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_mortgage_operations</code>.
     */
    public void setNumberOfMortgageOperations(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_mortgage_operations</code>.
     */
    public Long getNumberOfMortgageOperations() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_personal_loan_operations</code>.
     */
    public void setNumberOfPersonalLoanOperations(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_personal_loan_operations</code>.
     */
    public Long getNumberOfPersonalLoanOperations() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>spain_equifax.equifax.number_of_telco_operations</code>.
     */
    public void setNumberOfTelcoOperations(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.number_of_telco_operations</code>.
     */
    public Long getNumberOfTelcoOperations() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>spain_equifax.equifax.request_body</code>.
     */
    public void setRequestBody(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.request_body</code>.
     */
    public String getRequestBody() {
        return (String) get(18);
    }

    /**
     * Setter for <code>spain_equifax.equifax.response_body</code>.
     */
    public void setResponseBody(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.response_body</code>.
     */
    public String getResponseBody() {
        return (String) get(19);
    }

    /**
     * Setter for <code>spain_equifax.equifax.status</code>.
     */
    public void setStatus(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.status</code>.
     */
    public String getStatus() {
        return (String) get(20);
    }

    /**
     * Setter for <code>spain_equifax.equifax.total_number_of_operations</code>.
     */
    public void setTotalNumberOfOperations(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.total_number_of_operations</code>.
     */
    public Long getTotalNumberOfOperations() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>spain_equifax.equifax.total_number_of_other_unpaid</code>.
     */
    public void setTotalNumberOfOtherUnpaid(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.total_number_of_other_unpaid</code>.
     */
    public Long getTotalNumberOfOtherUnpaid() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>spain_equifax.equifax.total_unpaid_balance</code>.
     */
    public void setTotalUnpaidBalance(BigDecimal value) {
        set(23, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.total_unpaid_balance</code>.
     */
    public BigDecimal getTotalUnpaidBalance() {
        return (BigDecimal) get(23);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_consumer_credit</code>.
     */
    public void setUnpaidBalanceOfConsumerCredit(BigDecimal value) {
        set(24, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_consumer_credit</code>.
     */
    public BigDecimal getUnpaidBalanceOfConsumerCredit() {
        return (BigDecimal) get(24);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_credit_card</code>.
     */
    public void setUnpaidBalanceOfCreditCard(BigDecimal value) {
        set(25, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_credit_card</code>.
     */
    public BigDecimal getUnpaidBalanceOfCreditCard() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_mortgage</code>.
     */
    public void setUnpaidBalanceOfMortgage(BigDecimal value) {
        set(26, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_mortgage</code>.
     */
    public BigDecimal getUnpaidBalanceOfMortgage() {
        return (BigDecimal) get(26);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_other</code>.
     */
    public void setUnpaidBalanceOfOther(BigDecimal value) {
        set(27, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_other</code>.
     */
    public BigDecimal getUnpaidBalanceOfOther() {
        return (BigDecimal) get(27);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_other_products</code>.
     */
    public void setUnpaidBalanceOfOtherProducts(BigDecimal value) {
        set(28, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_other_products</code>.
     */
    public BigDecimal getUnpaidBalanceOfOtherProducts() {
        return (BigDecimal) get(28);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_personal_loan</code>.
     */
    public void setUnpaidBalanceOfPersonalLoan(BigDecimal value) {
        set(29, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_personal_loan</code>.
     */
    public BigDecimal getUnpaidBalanceOfPersonalLoan() {
        return (BigDecimal) get(29);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_of_telco</code>.
     */
    public void setUnpaidBalanceOfTelco(BigDecimal value) {
        set(30, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_of_telco</code>.
     */
    public BigDecimal getUnpaidBalanceOfTelco() {
        return (BigDecimal) get(30);
    }

    /**
     * Setter for <code>spain_equifax.equifax.unpaid_balance_own_entity</code>.
     */
    public void setUnpaidBalanceOwnEntity(BigDecimal value) {
        set(31, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.unpaid_balance_own_entity</code>.
     */
    public BigDecimal getUnpaidBalanceOwnEntity() {
        return (BigDecimal) get(31);
    }

    /**
     * Setter for <code>spain_equifax.equifax.worst_situation_code</code>.
     */
    public void setWorstSituationCode(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.worst_situation_code</code>.
     */
    public String getWorstSituationCode() {
        return (String) get(32);
    }

    /**
     * Setter for <code>spain_equifax.equifax.worst_unpaid_balance</code>.
     */
    public void setWorstUnpaidBalance(BigDecimal value) {
        set(33, value);
    }

    /**
     * Getter for <code>spain_equifax.equifax.worst_unpaid_balance</code>.
     */
    public BigDecimal getWorstUnpaidBalance() {
        return (BigDecimal) get(33);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EquifaxRecord
     */
    public EquifaxRecord() {
        super(Equifax.EQUIFAX);
    }

    /**
     * Create a detached, initialised EquifaxRecord
     */
    public EquifaxRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, Long applicationId, Long clientId, Long delincuencyDays, String documentNumber, String error, Long numberOfConsumerCreditOperations, Long numberOfCreditCardOperations, Long numberOfCreditors, Long numberOfDaysOfWorstSituation, Long numberOfMortgageOperations, Long numberOfPersonalLoanOperations, Long numberOfTelcoOperations, String requestBody, String responseBody, String status, Long totalNumberOfOperations, Long totalNumberOfOtherUnpaid, BigDecimal totalUnpaidBalance, BigDecimal unpaidBalanceOfConsumerCredit, BigDecimal unpaidBalanceOfCreditCard, BigDecimal unpaidBalanceOfMortgage, BigDecimal unpaidBalanceOfOther, BigDecimal unpaidBalanceOfOtherProducts, BigDecimal unpaidBalanceOfPersonalLoan, BigDecimal unpaidBalanceOfTelco, BigDecimal unpaidBalanceOwnEntity, String worstSituationCode, BigDecimal worstUnpaidBalance) {
        super(Equifax.EQUIFAX);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, applicationId);
        set(7, clientId);
        set(8, delincuencyDays);
        set(9, documentNumber);
        set(10, error);
        set(11, numberOfConsumerCreditOperations);
        set(12, numberOfCreditCardOperations);
        set(13, numberOfCreditors);
        set(14, numberOfDaysOfWorstSituation);
        set(15, numberOfMortgageOperations);
        set(16, numberOfPersonalLoanOperations);
        set(17, numberOfTelcoOperations);
        set(18, requestBody);
        set(19, responseBody);
        set(20, status);
        set(21, totalNumberOfOperations);
        set(22, totalNumberOfOtherUnpaid);
        set(23, totalUnpaidBalance);
        set(24, unpaidBalanceOfConsumerCredit);
        set(25, unpaidBalanceOfCreditCard);
        set(26, unpaidBalanceOfMortgage);
        set(27, unpaidBalanceOfOther);
        set(28, unpaidBalanceOfOtherProducts);
        set(29, unpaidBalanceOfPersonalLoan);
        set(30, unpaidBalanceOfTelco);
        set(31, unpaidBalanceOwnEntity);
        set(32, worstSituationCode);
        set(33, worstUnpaidBalance);
    }
}
