/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.alfa.tables.records;


import fintech.bo.db.jooq.alfa.tables.AlfaFeeStrategy;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlfaFeeStrategyRecord extends UpdatableRecordImpl<AlfaFeeStrategyRecord> implements Record9<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, BigDecimal, String> {

    private static final long serialVersionUID = 1011183211;

    /**
     * Setter for <code>alfa.alfa_fee_strategy.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.calculation_strategy_id</code>.
     */
    public void setCalculationStrategyId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.calculation_strategy_id</code>.
     */
    public Long getCalculationStrategyId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.fee_rate</code>.
     */
    public void setFeeRate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.fee_rate</code>.
     */
    public BigDecimal getFeeRate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>alfa.alfa_fee_strategy.company</code>.
     */
    public void setCompany(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>alfa.alfa_fee_strategy.company</code>.
     */
    public String getCompany() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, BigDecimal, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, BigDecimal, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.CALCULATION_STRATEGY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.FEE_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AlfaFeeStrategy.ALFA_FEE_STRATEGY.COMPANY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCalculationStrategyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getFeeRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value7(Long value) {
        setCalculationStrategyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value8(BigDecimal value) {
        setFeeRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord value9(String value) {
        setCompany(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaFeeStrategyRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, Long value7, BigDecimal value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlfaFeeStrategyRecord
     */
    public AlfaFeeStrategyRecord() {
        super(AlfaFeeStrategy.ALFA_FEE_STRATEGY);
    }

    /**
     * Create a detached, initialised AlfaFeeStrategyRecord
     */
    public AlfaFeeStrategyRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, Long calculationStrategyId, BigDecimal feeRate, String company) {
        super(AlfaFeeStrategy.ALFA_FEE_STRATEGY);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, calculationStrategyId);
        set(7, feeRate);
        set(8, company);
    }
}
