/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.crm.tables.records;


import fintech.bo.db.jooq.crm.tables.ClientAttribute;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientAttributeRecord extends UpdatableRecordImpl<ClientAttributeRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 23816940;

    /**
     * Setter for <code>crm.client_attribute.client_id</code>.
     */
    public void setClientId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>crm.client_attribute.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>crm.client_attribute.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>crm.client_attribute.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>crm.client_attribute.key</code>.
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>crm.client_attribute.key</code>.
     */
    public String getKey() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ClientAttribute.CLIENT_ATTRIBUTE.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ClientAttribute.CLIENT_ATTRIBUTE.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ClientAttribute.CLIENT_ATTRIBUTE.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientAttributeRecord value1(Long value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientAttributeRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientAttributeRecord value3(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientAttributeRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientAttributeRecord
     */
    public ClientAttributeRecord() {
        super(ClientAttribute.CLIENT_ATTRIBUTE);
    }

    /**
     * Create a detached, initialised ClientAttributeRecord
     */
    public ClientAttributeRecord(Long clientId, String value, String key) {
        super(ClientAttribute.CLIENT_ATTRIBUTE);

        set(0, clientId);
        set(1, value);
        set(2, key);
    }
}
