/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.crm.tables.records;


import fintech.bo.db.jooq.crm.tables.MarketingConsentLog;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketingConsentLogRecord extends TableRecordImpl<MarketingConsentLogRecord> implements Record11<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, LocalDateTime, Boolean, String, String> {

    private static final long serialVersionUID = -1278813098;

    /**
     * Setter for <code>crm.marketing_consent_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.client_id</code>.
     */
    public void setClientId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.value</code>.
     */
    public void setValue(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.value</code>.
     */
    public Boolean getValue() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.source</code>.
     */
    public void setSource(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.source</code>.
     */
    public String getSource() {
        return (String) get(9);
    }

    /**
     * Setter for <code>crm.marketing_consent_log.note</code>.
     */
    public void setNote(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>crm.marketing_consent_log.note</code>.
     */
    public String getNote() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, LocalDateTime, Boolean, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, LocalDateTime, String, Long, LocalDateTime, String, Long, LocalDateTime, Boolean, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return MarketingConsentLog.MARKETING_CONSENT_LOG.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value7(Long value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value8(LocalDateTime value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value9(Boolean value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value10(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord value11(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingConsentLogRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, Long value7, LocalDateTime value8, Boolean value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarketingConsentLogRecord
     */
    public MarketingConsentLogRecord() {
        super(MarketingConsentLog.MARKETING_CONSENT_LOG);
    }

    /**
     * Create a detached, initialised MarketingConsentLogRecord
     */
    public MarketingConsentLogRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, Long clientId, LocalDateTime timestamp, Boolean value, String source, String note) {
        super(MarketingConsentLog.MARKETING_CONSENT_LOG);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, clientId);
        set(7, timestamp);
        set(8, value);
        set(9, source);
        set(10, note);
    }
}
