/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.crm.tables;


import fintech.bo.db.jooq.crm.Crm;
import fintech.bo.db.jooq.crm.Keys;
import fintech.bo.db.jooq.crm.tables.records.VerifyEmailTokenRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerifyEmailToken extends TableImpl<VerifyEmailTokenRecord> {

    private static final long serialVersionUID = -659633729;

    /**
     * The reference instance of <code>crm.verify_email_token</code>
     */
    public static final VerifyEmailToken VERIFY_EMAIL_TOKEN = new VerifyEmailToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VerifyEmailTokenRecord> getRecordType() {
        return VerifyEmailTokenRecord.class;
    }

    /**
     * The column <code>crm.verify_email_token.id</code>.
     */
    public final TableField<VerifyEmailTokenRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.created_at</code>.
     */
    public final TableField<VerifyEmailTokenRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.created_by</code>.
     */
    public final TableField<VerifyEmailTokenRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>crm.verify_email_token.entity_version</code>.
     */
    public final TableField<VerifyEmailTokenRecord, Long> ENTITY_VERSION = createField("entity_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.updated_at</code>.
     */
    public final TableField<VerifyEmailTokenRecord, LocalDateTime> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.updated_by</code>.
     */
    public final TableField<VerifyEmailTokenRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>crm.verify_email_token.expires_at</code>.
     */
    public final TableField<VerifyEmailTokenRecord, LocalDateTime> EXPIRES_AT = createField("expires_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.token</code>.
     */
    public final TableField<VerifyEmailTokenRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.is_used</code>.
     */
    public final TableField<VerifyEmailTokenRecord, Boolean> IS_USED = createField("is_used", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>crm.verify_email_token.client_id</code>.
     */
    public final TableField<VerifyEmailTokenRecord, Long> CLIENT_ID = createField("client_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>crm.verify_email_token</code> table reference
     */
    public VerifyEmailToken() {
        this("verify_email_token", null);
    }

    /**
     * Create an aliased <code>crm.verify_email_token</code> table reference
     */
    public VerifyEmailToken(String alias) {
        this(alias, VERIFY_EMAIL_TOKEN);
    }

    private VerifyEmailToken(String alias, Table<VerifyEmailTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private VerifyEmailToken(String alias, Table<VerifyEmailTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Crm.CRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VerifyEmailTokenRecord> getPrimaryKey() {
        return Keys.VERIFY_EMAIL_TOKEN_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VerifyEmailTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<VerifyEmailTokenRecord>>asList(Keys.VERIFY_EMAIL_TOKEN_PKEY, Keys.UK_FNJ2PBPGSYMH6J0TQ0VQ3Q69V);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VerifyEmailTokenRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VerifyEmailTokenRecord, ?>>asList(Keys.VERIFY_EMAIL_TOKEN__FK_VERIFY_EMAIL_TOKEN_CLIENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyEmailToken as(String alias) {
        return new VerifyEmailToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VerifyEmailToken rename(String name) {
        return new VerifyEmailToken(name, null);
    }
}
