/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.dc;


import fintech.bo.db.jooq.dc.tables.Action;
import fintech.bo.db.jooq.dc.tables.Agent;
import fintech.bo.db.jooq.dc.tables.AgentAbsence;
import fintech.bo.db.jooq.dc.tables.AgentPortfolio;
import fintech.bo.db.jooq.dc.tables.Debt;
import fintech.bo.db.jooq.dc.tables.DebtImport;
import fintech.bo.db.jooq.dc.tables.Settings;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dc extends SchemaImpl {

    private static final long serialVersionUID = -415049467;

    /**
     * The reference instance of <code>dc</code>
     */
    public static final Dc DC = new Dc();

    /**
     * The table <code>dc.action</code>.
     */
    public final Action ACTION = fintech.bo.db.jooq.dc.tables.Action.ACTION;

    /**
     * The table <code>dc.agent</code>.
     */
    public final Agent AGENT = fintech.bo.db.jooq.dc.tables.Agent.AGENT;

    /**
     * The table <code>dc.agent_absence</code>.
     */
    public final AgentAbsence AGENT_ABSENCE = fintech.bo.db.jooq.dc.tables.AgentAbsence.AGENT_ABSENCE;

    /**
     * The table <code>dc.agent_portfolio</code>.
     */
    public final AgentPortfolio AGENT_PORTFOLIO = fintech.bo.db.jooq.dc.tables.AgentPortfolio.AGENT_PORTFOLIO;

    /**
     * The table <code>dc.debt</code>.
     */
    public final Debt DEBT = fintech.bo.db.jooq.dc.tables.Debt.DEBT;

    /**
     * The table <code>dc.debt_import</code>.
     */
    public final DebtImport DEBT_IMPORT = fintech.bo.db.jooq.dc.tables.DebtImport.DEBT_IMPORT;

    /**
     * The table <code>dc.settings</code>.
     */
    public final Settings SETTINGS = fintech.bo.db.jooq.dc.tables.Settings.SETTINGS;

    /**
     * No further instances allowed
     */
    private Dc() {
        super("dc", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Action.ACTION,
            Agent.AGENT,
            AgentAbsence.AGENT_ABSENCE,
            AgentPortfolio.AGENT_PORTFOLIO,
            Debt.DEBT,
            DebtImport.DEBT_IMPORT,
            Settings.SETTINGS);
    }
}
