/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.dc;


import fintech.bo.db.jooq.dc.tables.Action;
import fintech.bo.db.jooq.dc.tables.Agent;
import fintech.bo.db.jooq.dc.tables.AgentAbsence;
import fintech.bo.db.jooq.dc.tables.AgentPortfolio;
import fintech.bo.db.jooq.dc.tables.Debt;
import fintech.bo.db.jooq.dc.tables.DebtImport;
import fintech.bo.db.jooq.dc.tables.Settings;
import fintech.bo.db.jooq.dc.tables.records.ActionRecord;
import fintech.bo.db.jooq.dc.tables.records.AgentAbsenceRecord;
import fintech.bo.db.jooq.dc.tables.records.AgentPortfolioRecord;
import fintech.bo.db.jooq.dc.tables.records.AgentRecord;
import fintech.bo.db.jooq.dc.tables.records.DebtImportRecord;
import fintech.bo.db.jooq.dc.tables.records.DebtRecord;
import fintech.bo.db.jooq.dc.tables.records.SettingsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>dc</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActionRecord> ACTION_PKEY = UniqueKeys0.ACTION_PKEY;
    public static final UniqueKey<AgentRecord> AGENT_PKEY = UniqueKeys0.AGENT_PKEY;
    public static final UniqueKey<AgentRecord> UK_5IFYR83T40XPP54DY2DCDN6JU = UniqueKeys0.UK_5IFYR83T40XPP54DY2DCDN6JU;
    public static final UniqueKey<AgentAbsenceRecord> AGENT_ABSENCE_PKEY = UniqueKeys0.AGENT_ABSENCE_PKEY;
    public static final UniqueKey<DebtRecord> DEBT_PKEY = UniqueKeys0.DEBT_PKEY;
    public static final UniqueKey<DebtRecord> UK_C053GL0SKXQVJ93BDM77MGDF = UniqueKeys0.UK_C053GL0SKXQVJ93BDM77MGDF;
    public static final UniqueKey<DebtImportRecord> DEBT_IMPORT_PKEY = UniqueKeys0.DEBT_IMPORT_PKEY;
    public static final UniqueKey<SettingsRecord> SETTINGS_PKEY = UniqueKeys0.SETTINGS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ActionRecord, DebtRecord> ACTION__FKFK0TOX5YV4PRL8Q7EGM6LQLSX = ForeignKeys0.ACTION__FKFK0TOX5YV4PRL8Q7EGM6LQLSX;
    public static final ForeignKey<AgentAbsenceRecord, AgentRecord> AGENT_ABSENCE__FKM0MFQM1BET67Y00UKSFRNTA6E = ForeignKeys0.AGENT_ABSENCE__FKM0MFQM1BET67Y00UKSFRNTA6E;
    public static final ForeignKey<AgentPortfolioRecord, AgentRecord> AGENT_PORTFOLIO__FK8C04TA12JLS514T7PFFYE9SDE = ForeignKeys0.AGENT_PORTFOLIO__FK8C04TA12JLS514T7PFFYE9SDE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ActionRecord> ACTION_PKEY = createUniqueKey(Action.ACTION, "action_pkey", Action.ACTION.ID);
        public static final UniqueKey<AgentRecord> AGENT_PKEY = createUniqueKey(Agent.AGENT, "agent_pkey", Agent.AGENT.ID);
        public static final UniqueKey<AgentRecord> UK_5IFYR83T40XPP54DY2DCDN6JU = createUniqueKey(Agent.AGENT, "uk_5ifyr83t40xpp54dy2dcdn6ju", Agent.AGENT.AGENT_);
        public static final UniqueKey<AgentAbsenceRecord> AGENT_ABSENCE_PKEY = createUniqueKey(AgentAbsence.AGENT_ABSENCE, "agent_absence_pkey", AgentAbsence.AGENT_ABSENCE.ID);
        public static final UniqueKey<DebtRecord> DEBT_PKEY = createUniqueKey(Debt.DEBT, "debt_pkey", Debt.DEBT.ID);
        public static final UniqueKey<DebtRecord> UK_C053GL0SKXQVJ93BDM77MGDF = createUniqueKey(Debt.DEBT, "uk_c053gl0skxqvj93bdm77mgdf", Debt.DEBT.LOAN_NUMBER);
        public static final UniqueKey<DebtImportRecord> DEBT_IMPORT_PKEY = createUniqueKey(DebtImport.DEBT_IMPORT, "debt_import_pkey", DebtImport.DEBT_IMPORT.ID);
        public static final UniqueKey<SettingsRecord> SETTINGS_PKEY = createUniqueKey(Settings.SETTINGS, "settings_pkey", Settings.SETTINGS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ActionRecord, DebtRecord> ACTION__FKFK0TOX5YV4PRL8Q7EGM6LQLSX = createForeignKey(fintech.bo.db.jooq.dc.Keys.DEBT_PKEY, Action.ACTION, "action__fkfk0tox5yv4prl8q7egm6lqlsx", Action.ACTION.DEBT_ID);
        public static final ForeignKey<AgentAbsenceRecord, AgentRecord> AGENT_ABSENCE__FKM0MFQM1BET67Y00UKSFRNTA6E = createForeignKey(fintech.bo.db.jooq.dc.Keys.AGENT_PKEY, AgentAbsence.AGENT_ABSENCE, "agent_absence__fkm0mfqm1bet67y00uksfrnta6e", AgentAbsence.AGENT_ABSENCE.AGENT_ID);
        public static final ForeignKey<AgentPortfolioRecord, AgentRecord> AGENT_PORTFOLIO__FK8C04TA12JLS514T7PFFYE9SDE = createForeignKey(fintech.bo.db.jooq.dc.Keys.AGENT_PKEY, AgentPortfolio.AGENT_PORTFOLIO, "agent_portfolio__fk8c04ta12jls514t7pffye9sde", AgentPortfolio.AGENT_PORTFOLIO.AGENT_ID);
    }
}
