/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.dc;


import fintech.bo.db.jooq.dc.tables.Action;
import fintech.bo.db.jooq.dc.tables.Agent;
import fintech.bo.db.jooq.dc.tables.AgentAbsence;
import fintech.bo.db.jooq.dc.tables.AgentPortfolio;
import fintech.bo.db.jooq.dc.tables.Debt;
import fintech.bo.db.jooq.dc.tables.DebtImport;
import fintech.bo.db.jooq.dc.tables.Settings;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dc
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dc.action</code>.
     */
    public static final Action ACTION = fintech.bo.db.jooq.dc.tables.Action.ACTION;

    /**
     * The table <code>dc.agent</code>.
     */
    public static final Agent AGENT = fintech.bo.db.jooq.dc.tables.Agent.AGENT;

    /**
     * The table <code>dc.agent_absence</code>.
     */
    public static final AgentAbsence AGENT_ABSENCE = fintech.bo.db.jooq.dc.tables.AgentAbsence.AGENT_ABSENCE;

    /**
     * The table <code>dc.agent_portfolio</code>.
     */
    public static final AgentPortfolio AGENT_PORTFOLIO = fintech.bo.db.jooq.dc.tables.AgentPortfolio.AGENT_PORTFOLIO;

    /**
     * The table <code>dc.debt</code>.
     */
    public static final Debt DEBT = fintech.bo.db.jooq.dc.tables.Debt.DEBT;

    /**
     * The table <code>dc.debt_import</code>.
     */
    public static final DebtImport DEBT_IMPORT = fintech.bo.db.jooq.dc.tables.DebtImport.DEBT_IMPORT;

    /**
     * The table <code>dc.settings</code>.
     */
    public static final Settings SETTINGS = fintech.bo.db.jooq.dc.tables.Settings.SETTINGS;
}
