/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.rule;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in rule
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>rule.rule_log_id_seq</code>
     */
    public static final Sequence<Long> RULE_LOG_ID_SEQ = new SequenceImpl<Long>("rule_log_id_seq", Rule.RULE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>rule.rule_set_log_id_seq</code>
     */
    public static final Sequence<Long> RULE_SET_LOG_ID_SEQ = new SequenceImpl<Long>("rule_set_log_id_seq", Rule.RULE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
