/*
 * This file is generated by jOOQ.
*/
package fintech.bo.spain.db.jooq.experian.tables;


import fintech.bo.spain.db.jooq.experian.Keys;
import fintech.bo.spain.db.jooq.experian.SpainExperian;
import fintech.bo.spain.db.jooq.experian.tables.records.CaisResumenRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaisResumen extends TableImpl<CaisResumenRecord> {

    private static final long serialVersionUID = -1078949097;

    /**
     * The reference instance of <code>spain_experian.cais_resumen</code>
     */
    public static final CaisResumen CAIS_RESUMEN = new CaisResumen();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CaisResumenRecord> getRecordType() {
        return CaisResumenRecord.class;
    }

    /**
     * The column <code>spain_experian.cais_resumen.id</code>.
     */
    public final TableField<CaisResumenRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.created_at</code>.
     */
    public final TableField<CaisResumenRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.created_by</code>.
     */
    public final TableField<CaisResumenRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.entity_version</code>.
     */
    public final TableField<CaisResumenRecord, Long> ENTITY_VERSION = createField("entity_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.updated_at</code>.
     */
    public final TableField<CaisResumenRecord, LocalDateTime> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.updated_by</code>.
     */
    public final TableField<CaisResumenRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.application_id</code>.
     */
    public final TableField<CaisResumenRecord, Long> APPLICATION_ID = createField("application_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.client_id</code>.
     */
    public final TableField<CaisResumenRecord, Long> CLIENT_ID = createField("client_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.document_number</code>.
     */
    public final TableField<CaisResumenRecord, String> DOCUMENT_NUMBER = createField("document_number", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.error</code>.
     */
    public final TableField<CaisResumenRecord, String> ERROR = createField("error", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.importe_total_impagado</code>.
     */
    public final TableField<CaisResumenRecord, BigDecimal> IMPORTE_TOTAL_IMPAGADO = createField("importe_total_impagado", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 2), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.maximo_importe_impagado</code>.
     */
    public final TableField<CaisResumenRecord, BigDecimal> MAXIMO_IMPORTE_IMPAGADO = createField("maximo_importe_impagado", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 2), this, "");

    /**
     * The column <code>spain_experian.cais_resumen.numero_total_cuotas_impagadas</code>.
     */
    public final TableField<CaisResumenRecord, Integer> NUMERO_TOTAL_CUOTAS_IMPAGADAS = createField("numero_total_cuotas_impagadas", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.numero_total_operaciones_impagadas</code>.
     */
    public final TableField<CaisResumenRecord, Integer> NUMERO_TOTAL_OPERACIONES_IMPAGADAS = createField("numero_total_operaciones_impagadas", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.peor_situacion_pago</code>.
     */
    public final TableField<CaisResumenRecord, String> PEOR_SITUACION_PAGO = createField("peor_situacion_pago", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.peor_situacion_pago_historica</code>.
     */
    public final TableField<CaisResumenRecord, String> PEOR_SITUACION_PAGO_HISTORICA = createField("peor_situacion_pago_historica", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.provincia_codigo</code>.
     */
    public final TableField<CaisResumenRecord, String> PROVINCIA_CODIGO = createField("provincia_codigo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.request_body</code>.
     */
    public final TableField<CaisResumenRecord, String> REQUEST_BODY = createField("request_body", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.response_body</code>.
     */
    public final TableField<CaisResumenRecord, String> RESPONSE_BODY = createField("response_body", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>spain_experian.cais_resumen.status</code>.
     */
    public final TableField<CaisResumenRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>spain_experian.cais_resumen</code> table reference
     */
    public CaisResumen() {
        this("cais_resumen", null);
    }

    /**
     * Create an aliased <code>spain_experian.cais_resumen</code> table reference
     */
    public CaisResumen(String alias) {
        this(alias, CAIS_RESUMEN);
    }

    private CaisResumen(String alias, Table<CaisResumenRecord> aliased) {
        this(alias, aliased, null);
    }

    private CaisResumen(String alias, Table<CaisResumenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpainExperian.SPAIN_EXPERIAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CaisResumenRecord> getPrimaryKey() {
        return Keys.CAIS_RESUMEN_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CaisResumenRecord>> getKeys() {
        return Arrays.<UniqueKey<CaisResumenRecord>>asList(Keys.CAIS_RESUMEN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaisResumen as(String alias) {
        return new CaisResumen(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CaisResumen rename(String name) {
        return new CaisResumen(name, null);
    }
}
