/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.dc.tables.records;


import fintech.bo.db.jooq.dc.tables.AgentPortfolio;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgentPortfolioRecord extends TableRecordImpl<AgentPortfolioRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 631768327;

    /**
     * Setter for <code>dc.agent_portfolio.agent_id</code>.
     */
    public void setAgentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dc.agent_portfolio.agent_id</code>.
     */
    public Long getAgentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dc.agent_portfolio.portfolios</code>.
     */
    public void setPortfolios(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dc.agent_portfolio.portfolios</code>.
     */
    public String getPortfolios() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AgentPortfolio.AGENT_PORTFOLIO.AGENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AgentPortfolio.AGENT_PORTFOLIO.PORTFOLIOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAgentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPortfolios();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgentPortfolioRecord value1(Long value) {
        setAgentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgentPortfolioRecord value2(String value) {
        setPortfolios(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgentPortfolioRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentPortfolioRecord
     */
    public AgentPortfolioRecord() {
        super(AgentPortfolio.AGENT_PORTFOLIO);
    }

    /**
     * Create a detached, initialised AgentPortfolioRecord
     */
    public AgentPortfolioRecord(Long agentId, String portfolios) {
        super(AgentPortfolio.AGENT_PORTFOLIO);

        set(0, agentId);
        set(1, portfolios);
    }
}
