/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.sms;


import fintech.bo.db.jooq.sms.tables.Incoming;
import fintech.bo.db.jooq.sms.tables.Log;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sms extends SchemaImpl {

    private static final long serialVersionUID = 2104914005;

    /**
     * The reference instance of <code>sms</code>
     */
    public static final Sms SMS = new Sms();

    /**
     * The table <code>sms.incoming</code>.
     */
    public final Incoming INCOMING = fintech.bo.db.jooq.sms.tables.Incoming.INCOMING;

    /**
     * The table <code>sms.log</code>.
     */
    public final Log LOG = fintech.bo.db.jooq.sms.tables.Log.LOG;

    /**
     * No further instances allowed
     */
    private Sms() {
        super("sms", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Incoming.INCOMING,
            Log.LOG);
    }
}
