/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.alfa;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in alfa
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>alfa.address_id_seq</code>
     */
    public static final Sequence<Long> ADDRESS_ID_SEQ = new SequenceImpl<Long>("address_id_seq", Alfa.ALFA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>alfa.loc_batch_sequence</code>
     */
    public static final Sequence<Long> LOC_BATCH_SEQUENCE = new SequenceImpl<Long>("loc_batch_sequence", Alfa.ALFA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
