/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.marketing.tables;


import fintech.bo.db.jooq.marketing.Keys;
import fintech.bo.db.jooq.marketing.Marketing;
import fintech.bo.db.jooq.marketing.tables.records.MarketingCommunicationRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketingCommunication extends TableImpl<MarketingCommunicationRecord> {

    private static final long serialVersionUID = 1618874605;

    /**
     * The reference instance of <code>marketing.marketing_communication</code>
     */
    public static final MarketingCommunication MARKETING_COMMUNICATION = new MarketingCommunication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarketingCommunicationRecord> getRecordType() {
        return MarketingCommunicationRecord.class;
    }

    /**
     * The column <code>marketing.marketing_communication.id</code>.
     */
    public final TableField<MarketingCommunicationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.marketing_campaign_id</code>.
     */
    public final TableField<MarketingCommunicationRecord, Long> MARKETING_CAMPAIGN_ID = createField("marketing_campaign_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.created_at</code>.
     */
    public final TableField<MarketingCommunicationRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.created_by</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>marketing.marketing_communication.entity_version</code>.
     */
    public final TableField<MarketingCommunicationRecord, Long> ENTITY_VERSION = createField("entity_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.updated_at</code>.
     */
    public final TableField<MarketingCommunicationRecord, LocalDateTime> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.updated_by</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>marketing.marketing_communication.status</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.email_subject</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> EMAIL_SUBJECT = createField("email_subject", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.email_body</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> EMAIL_BODY = createField("email_body", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.sms</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> SMS = createField("sms", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>marketing.marketing_communication.audience_settings_json_config</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> AUDIENCE_SETTINGS_JSON_CONFIG = createField("audience_settings_json_config", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.promo_code_id</code>.
     */
    public final TableField<MarketingCommunicationRecord, Long> PROMO_CODE_ID = createField("promo_code_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>marketing.marketing_communication.next_action_at</code>.
     */
    public final TableField<MarketingCommunicationRecord, LocalDateTime> NEXT_ACTION_AT = createField("next_action_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>marketing.marketing_communication.reminder</code>.
     */
    public final TableField<MarketingCommunicationRecord, Boolean> REMINDER = createField("reminder", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.click_rate</code>.
     */
    public final TableField<MarketingCommunicationRecord, BigDecimal> CLICK_RATE = createField("click_rate", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 4), this, "");

    /**
     * The column <code>marketing.marketing_communication.view_rate</code>.
     */
    public final TableField<MarketingCommunicationRecord, BigDecimal> VIEW_RATE = createField("view_rate", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 4), this, "");

    /**
     * The column <code>marketing.marketing_communication.targeted_users</code>.
     */
    public final TableField<MarketingCommunicationRecord, Integer> TARGETED_USERS = createField("targeted_users", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>marketing.marketing_communication.image_file_id</code>.
     */
    public final TableField<MarketingCommunicationRecord, Long> IMAGE_FILE_ID = createField("image_file_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>marketing.marketing_communication.last_execution_result</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> LAST_EXECUTION_RESULT = createField("last_execution_result", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>marketing.marketing_communication.views_hll_hex</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> VIEWS_HLL_HEX = createField("views_hll_hex", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>marketing.marketing_communication.clicks_hll_hex</code>.
     */
    public final TableField<MarketingCommunicationRecord, String> CLICKS_HLL_HEX = createField("clicks_hll_hex", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>marketing.marketing_communication</code> table reference
     */
    public MarketingCommunication() {
        this("marketing_communication", null);
    }

    /**
     * Create an aliased <code>marketing.marketing_communication</code> table reference
     */
    public MarketingCommunication(String alias) {
        this(alias, MARKETING_COMMUNICATION);
    }

    private MarketingCommunication(String alias, Table<MarketingCommunicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private MarketingCommunication(String alias, Table<MarketingCommunicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Marketing.MARKETING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MarketingCommunicationRecord> getPrimaryKey() {
        return Keys.MARKETING_COMMUNICATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MarketingCommunicationRecord>> getKeys() {
        return Arrays.<UniqueKey<MarketingCommunicationRecord>>asList(Keys.MARKETING_COMMUNICATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MarketingCommunicationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MarketingCommunicationRecord, ?>>asList(Keys.MARKETING_COMMUNICATION__FK_MARKETING_CAMPAIGN_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingCommunication as(String alias) {
        return new MarketingCommunication(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MarketingCommunication rename(String name) {
        return new MarketingCommunication(name, null);
    }
}
