/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.strategy;


import fintech.bo.db.jooq.strategy.tables.CalculationStrategy;
import fintech.bo.db.jooq.strategy.tables.records.CalculationStrategyRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>strategy</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CalculationStrategyRecord> CALCULATION_STRATEGY_PKEY = UniqueKeys0.CALCULATION_STRATEGY_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CalculationStrategyRecord> CALCULATION_STRATEGY_PKEY = createUniqueKey(CalculationStrategy.CALCULATION_STRATEGY, "calculation_strategy_pkey", CalculationStrategy.CALCULATION_STRATEGY.ID);
    }
}
