/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.strategy;


import fintech.bo.db.jooq.strategy.tables.CalculationStrategy;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in strategy
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>strategy.calculation_strategy</code>.
     */
    public static final CalculationStrategy CALCULATION_STRATEGY = fintech.bo.db.jooq.strategy.tables.CalculationStrategy.CALCULATION_STRATEGY;
}
