/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.alfa.tables;


import fintech.bo.db.jooq.alfa.Alfa;
import fintech.bo.db.jooq.alfa.Keys;
import fintech.bo.db.jooq.alfa.tables.records.AlfaDailyPenaltyStrategyRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlfaDailyPenaltyStrategy extends TableImpl<AlfaDailyPenaltyStrategyRecord> {

    private static final long serialVersionUID = 994851160;

    /**
     * The reference instance of <code>alfa.alfa_daily_penalty_strategy</code>
     */
    public static final AlfaDailyPenaltyStrategy ALFA_DAILY_PENALTY_STRATEGY = new AlfaDailyPenaltyStrategy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlfaDailyPenaltyStrategyRecord> getRecordType() {
        return AlfaDailyPenaltyStrategyRecord.class;
    }

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.id</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.created_at</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.created_by</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.entity_version</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, Long> ENTITY_VERSION = createField("entity_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.updated_at</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, LocalDateTime> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.updated_by</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.calculation_strategy_id</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, Long> CALCULATION_STRATEGY_ID = createField("calculation_strategy_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_daily_penalty_strategy.penalty_rate</code>.
     */
    public final TableField<AlfaDailyPenaltyStrategyRecord, BigDecimal> PENALTY_RATE = createField("penalty_rate", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 2).nullable(false), this, "");

    /**
     * Create a <code>alfa.alfa_daily_penalty_strategy</code> table reference
     */
    public AlfaDailyPenaltyStrategy() {
        this("alfa_daily_penalty_strategy", null);
    }

    /**
     * Create an aliased <code>alfa.alfa_daily_penalty_strategy</code> table reference
     */
    public AlfaDailyPenaltyStrategy(String alias) {
        this(alias, ALFA_DAILY_PENALTY_STRATEGY);
    }

    private AlfaDailyPenaltyStrategy(String alias, Table<AlfaDailyPenaltyStrategyRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlfaDailyPenaltyStrategy(String alias, Table<AlfaDailyPenaltyStrategyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Alfa.ALFA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlfaDailyPenaltyStrategyRecord> getPrimaryKey() {
        return Keys.ALFA_DAILY_PENALTY_STRATEGY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlfaDailyPenaltyStrategyRecord>> getKeys() {
        return Arrays.<UniqueKey<AlfaDailyPenaltyStrategyRecord>>asList(Keys.ALFA_DAILY_PENALTY_STRATEGY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaDailyPenaltyStrategy as(String alias) {
        return new AlfaDailyPenaltyStrategy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlfaDailyPenaltyStrategy rename(String name) {
        return new AlfaDailyPenaltyStrategy(name, null);
    }
}
