/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.alfa.tables;


import fintech.bo.db.jooq.alfa.Alfa;
import fintech.bo.db.jooq.alfa.Keys;
import fintech.bo.db.jooq.alfa.tables.records.AlfaMonthlyInterestStrategyRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlfaMonthlyInterestStrategy extends TableImpl<AlfaMonthlyInterestStrategyRecord> {

    private static final long serialVersionUID = -132376743;

    /**
     * The reference instance of <code>alfa.alfa_monthly_interest_strategy</code>
     */
    public static final AlfaMonthlyInterestStrategy ALFA_MONTHLY_INTEREST_STRATEGY = new AlfaMonthlyInterestStrategy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlfaMonthlyInterestStrategyRecord> getRecordType() {
        return AlfaMonthlyInterestStrategyRecord.class;
    }

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.id</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.created_at</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.created_by</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.entity_version</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, Long> ENTITY_VERSION = createField("entity_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.updated_at</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, LocalDateTime> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.updated_by</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.calculation_strategy_id</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, Long> CALCULATION_STRATEGY_ID = createField("calculation_strategy_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.interest_rate</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, BigDecimal> INTEREST_RATE = createField("interest_rate", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 2).nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.using_decision_engine</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, Boolean> USING_DECISION_ENGINE = createField("using_decision_engine", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>alfa.alfa_monthly_interest_strategy.scenario</code>.
     */
    public final TableField<AlfaMonthlyInterestStrategyRecord, String> SCENARIO = createField("scenario", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>alfa.alfa_monthly_interest_strategy</code> table reference
     */
    public AlfaMonthlyInterestStrategy() {
        this("alfa_monthly_interest_strategy", null);
    }

    /**
     * Create an aliased <code>alfa.alfa_monthly_interest_strategy</code> table reference
     */
    public AlfaMonthlyInterestStrategy(String alias) {
        this(alias, ALFA_MONTHLY_INTEREST_STRATEGY);
    }

    private AlfaMonthlyInterestStrategy(String alias, Table<AlfaMonthlyInterestStrategyRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlfaMonthlyInterestStrategy(String alias, Table<AlfaMonthlyInterestStrategyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Alfa.ALFA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlfaMonthlyInterestStrategyRecord> getPrimaryKey() {
        return Keys.ALFA_MONTHLY_INTEREST_STRATEGY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlfaMonthlyInterestStrategyRecord>> getKeys() {
        return Arrays.<UniqueKey<AlfaMonthlyInterestStrategyRecord>>asList(Keys.ALFA_MONTHLY_INTEREST_STRATEGY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaMonthlyInterestStrategy as(String alias) {
        return new AlfaMonthlyInterestStrategy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlfaMonthlyInterestStrategy rename(String name) {
        return new AlfaMonthlyInterestStrategy(name, null);
    }
}
