/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.alfa.tables;


import fintech.bo.db.jooq.alfa.Alfa;
import fintech.bo.db.jooq.alfa.Keys;
import fintech.bo.db.jooq.alfa.tables.records.AlfaDpdPenaltyStrategyRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlfaDpdPenaltyStrategy extends TableImpl<AlfaDpdPenaltyStrategyRecord> {

    private static final long serialVersionUID = -1870082282;

    /**
     * The reference instance of <code>alfa.alfa_dpd_penalty_strategy</code>
     */
    public static final AlfaDpdPenaltyStrategy ALFA_DPD_PENALTY_STRATEGY = new AlfaDpdPenaltyStrategy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlfaDpdPenaltyStrategyRecord> getRecordType() {
        return AlfaDpdPenaltyStrategyRecord.class;
    }

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.id</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.created_at</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.created_by</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.entity_version</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, Long> ENTITY_VERSION = createField("entity_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.updated_at</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, LocalDateTime> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.updated_by</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>alfa.alfa_dpd_penalty_strategy.calculation_strategy_id</code>.
     */
    public final TableField<AlfaDpdPenaltyStrategyRecord, Long> CALCULATION_STRATEGY_ID = createField("calculation_strategy_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>alfa.alfa_dpd_penalty_strategy</code> table reference
     */
    public AlfaDpdPenaltyStrategy() {
        this("alfa_dpd_penalty_strategy", null);
    }

    /**
     * Create an aliased <code>alfa.alfa_dpd_penalty_strategy</code> table reference
     */
    public AlfaDpdPenaltyStrategy(String alias) {
        this(alias, ALFA_DPD_PENALTY_STRATEGY);
    }

    private AlfaDpdPenaltyStrategy(String alias, Table<AlfaDpdPenaltyStrategyRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlfaDpdPenaltyStrategy(String alias, Table<AlfaDpdPenaltyStrategyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Alfa.ALFA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlfaDpdPenaltyStrategyRecord> getPrimaryKey() {
        return Keys.ALFA_DPD_PENALTY_STRATEGY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlfaDpdPenaltyStrategyRecord>> getKeys() {
        return Arrays.<UniqueKey<AlfaDpdPenaltyStrategyRecord>>asList(Keys.ALFA_DPD_PENALTY_STRATEGY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlfaDpdPenaltyStrategy as(String alias) {
        return new AlfaDpdPenaltyStrategy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlfaDpdPenaltyStrategy rename(String name) {
        return new AlfaDpdPenaltyStrategy(name, null);
    }
}
