/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.lending.tables.records;


import fintech.bo.db.jooq.lending.tables.CreditLimit;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditLimitRecord extends UpdatableRecordImpl<CreditLimitRecord> implements Record10<Long, LocalDateTime, String, Long, LocalDateTime, String, LocalDate, Long, BigDecimal, String> {

    private static final long serialVersionUID = 580195867;

    /**
     * Setter for <code>lending.credit_limit.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lending.credit_limit.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lending.credit_limit.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>lending.credit_limit.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>lending.credit_limit.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lending.credit_limit.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lending.credit_limit.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>lending.credit_limit.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>lending.credit_limit.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>lending.credit_limit.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>lending.credit_limit.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lending.credit_limit.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lending.credit_limit.active_from</code>.
     */
    public void setActiveFrom(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>lending.credit_limit.active_from</code>.
     */
    public LocalDate getActiveFrom() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>lending.credit_limit.client_id</code>.
     */
    public void setClientId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>lending.credit_limit.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>lending.credit_limit.credit_limit</code>.
     */
    public void setCreditLimit(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>lending.credit_limit.credit_limit</code>.
     */
    public BigDecimal getCreditLimit() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>lending.credit_limit.reason</code>.
     */
    public void setReason(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>lending.credit_limit.reason</code>.
     */
    public String getReason() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, LocalDateTime, String, Long, LocalDateTime, String, LocalDate, Long, BigDecimal, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, LocalDateTime, String, Long, LocalDateTime, String, LocalDate, Long, BigDecimal, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CreditLimit.CREDIT_LIMIT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return CreditLimit.CREDIT_LIMIT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CreditLimit.CREDIT_LIMIT.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return CreditLimit.CREDIT_LIMIT.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return CreditLimit.CREDIT_LIMIT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CreditLimit.CREDIT_LIMIT.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field7() {
        return CreditLimit.CREDIT_LIMIT.ACTIVE_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return CreditLimit.CREDIT_LIMIT.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return CreditLimit.CREDIT_LIMIT.CREDIT_LIMIT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CreditLimit.CREDIT_LIMIT.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value7() {
        return getActiveFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getCreditLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value7(LocalDate value) {
        setActiveFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value8(Long value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value9(BigDecimal value) {
        setCreditLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord value10(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditLimitRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, LocalDate value7, Long value8, BigDecimal value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CreditLimitRecord
     */
    public CreditLimitRecord() {
        super(CreditLimit.CREDIT_LIMIT);
    }

    /**
     * Create a detached, initialised CreditLimitRecord
     */
    public CreditLimitRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, LocalDate activeFrom, Long clientId, BigDecimal creditLimit, String reason) {
        super(CreditLimit.CREDIT_LIMIT);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, activeFrom);
        set(7, clientId);
        set(8, creditLimit);
        set(9, reason);
    }
}
