/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.storage;


import fintech.bo.db.jooq.storage.tables.CloudFile;
import fintech.bo.db.jooq.storage.tables.records.CloudFileRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>storage</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CloudFileRecord, Long> IDENTITY_CLOUD_FILE = Identities0.IDENTITY_CLOUD_FILE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CloudFileRecord> CLOUD_FILE_PKEY = UniqueKeys0.CLOUD_FILE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CloudFileRecord, Long> IDENTITY_CLOUD_FILE = createIdentity(CloudFile.CLOUD_FILE, CloudFile.CLOUD_FILE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CloudFileRecord> CLOUD_FILE_PKEY = createUniqueKey(CloudFile.CLOUD_FILE, "cloud_file_pkey", CloudFile.CLOUD_FILE.ID);
    }
}
