/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.workflow.tables;


import fintech.bo.db.jooq.workflow.Keys;
import fintech.bo.db.jooq.workflow.Workflow;
import fintech.bo.db.jooq.workflow.tables.records.WorkflowAttributeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowAttribute extends TableImpl<WorkflowAttributeRecord> {

    private static final long serialVersionUID = -1804526421;

    /**
     * The reference instance of <code>workflow.workflow_attribute</code>
     */
    public static final WorkflowAttribute WORKFLOW_ATTRIBUTE = new WorkflowAttribute();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkflowAttributeRecord> getRecordType() {
        return WorkflowAttributeRecord.class;
    }

    /**
     * The column <code>workflow.workflow_attribute.workflow_id</code>.
     */
    public final TableField<WorkflowAttributeRecord, Long> WORKFLOW_ID = createField("workflow_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>workflow.workflow_attribute.value</code>.
     */
    public final TableField<WorkflowAttributeRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>workflow.workflow_attribute.key</code>.
     */
    public final TableField<WorkflowAttributeRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>workflow.workflow_attribute</code> table reference
     */
    public WorkflowAttribute() {
        this("workflow_attribute", null);
    }

    /**
     * Create an aliased <code>workflow.workflow_attribute</code> table reference
     */
    public WorkflowAttribute(String alias) {
        this(alias, WORKFLOW_ATTRIBUTE);
    }

    private WorkflowAttribute(String alias, Table<WorkflowAttributeRecord> aliased) {
        this(alias, aliased, null);
    }

    private WorkflowAttribute(String alias, Table<WorkflowAttributeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Workflow.WORKFLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WorkflowAttributeRecord> getPrimaryKey() {
        return Keys.WORKFLOW_ATTRIBUTE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WorkflowAttributeRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkflowAttributeRecord>>asList(Keys.WORKFLOW_ATTRIBUTE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WorkflowAttributeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WorkflowAttributeRecord, ?>>asList(Keys.WORKFLOW_ATTRIBUTE__FK_WORKFLOW_ATTRIBUTE_WORKFLOW_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkflowAttribute as(String alias) {
        return new WorkflowAttribute(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowAttribute rename(String name) {
        return new WorkflowAttribute(name, null);
    }
}
