/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.security.tables.records;


import fintech.bo.db.jooq.security.tables.RolePermission;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissionRecord extends TableRecordImpl<RolePermissionRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1928402083;

    /**
     * Setter for <code>security.role_permission.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>security.role_permission.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>security.role_permission.permission_id</code>.
     */
    public void setPermissionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>security.role_permission.permission_id</code>.
     */
    public Long getPermissionId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RolePermission.ROLE_PERMISSION.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RolePermission.ROLE_PERMISSION.PERMISSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPermissionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePermissionRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePermissionRecord value2(Long value) {
        setPermissionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePermissionRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionRecord
     */
    public RolePermissionRecord() {
        super(RolePermission.ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    public RolePermissionRecord(Long roleId, Long permissionId) {
        super(RolePermission.ROLE_PERMISSION);

        set(0, roleId);
        set(1, permissionId);
    }
}
