/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.payment.tables.records;


import fintech.bo.db.jooq.payment.tables.Institution;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstitutionRecord extends UpdatableRecordImpl<InstitutionRecord> implements Record16<Long, LocalDateTime, String, Long, LocalDateTime, String, String, String, String, Boolean, String, String, String, Boolean, String, String> {

    private static final long serialVersionUID = 805912876;

    /**
     * Setter for <code>payment.institution.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>payment.institution.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>payment.institution.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>payment.institution.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>payment.institution.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>payment.institution.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>payment.institution.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>payment.institution.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>payment.institution.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>payment.institution.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>payment.institution.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>payment.institution.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>payment.institution.institution_type</code>.
     */
    public void setInstitutionType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>payment.institution.institution_type</code>.
     */
    public String getInstitutionType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>payment.institution.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>payment.institution.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>payment.institution.payment_methods</code>.
     */
    public void setPaymentMethods(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>payment.institution.payment_methods</code>.
     */
    public String getPaymentMethods() {
        return (String) get(8);
    }

    /**
     * Setter for <code>payment.institution.is_primary</code>.
     */
    public void setIsPrimary(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>payment.institution.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>payment.institution.statement_export_format</code>.
     */
    public void setStatementExportFormat(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>payment.institution.statement_export_format</code>.
     */
    public String getStatementExportFormat() {
        return (String) get(10);
    }

    /**
     * Setter for <code>payment.institution.statement_export_params_json</code>.
     */
    public void setStatementExportParamsJson(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>payment.institution.statement_export_params_json</code>.
     */
    public String getStatementExportParamsJson() {
        return (String) get(11);
    }

    /**
     * Setter for <code>payment.institution.statement_import_format</code>.
     */
    public void setStatementImportFormat(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>payment.institution.statement_import_format</code>.
     */
    public String getStatementImportFormat() {
        return (String) get(12);
    }

    /**
     * Setter for <code>payment.institution.disabled</code>.
     */
    public void setDisabled(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>payment.institution.disabled</code>.
     */
    public Boolean getDisabled() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>payment.institution.code</code>.
     */
    public void setCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>payment.institution.code</code>.
     */
    public String getCode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>payment.institution.statement_api_exporter</code>.
     */
    public void setStatementApiExporter(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>payment.institution.statement_api_exporter</code>.
     */
    public String getStatementApiExporter() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, LocalDateTime, String, Long, LocalDateTime, String, String, String, String, Boolean, String, String, String, Boolean, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, LocalDateTime, String, Long, LocalDateTime, String, String, String, String, Boolean, String, String, String, Boolean, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Institution.INSTITUTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return Institution.INSTITUTION.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Institution.INSTITUTION.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Institution.INSTITUTION.ENTITY_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return Institution.INSTITUTION.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Institution.INSTITUTION.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Institution.INSTITUTION.INSTITUTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Institution.INSTITUTION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Institution.INSTITUTION.PAYMENT_METHODS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Institution.INSTITUTION.IS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Institution.INSTITUTION.STATEMENT_EXPORT_FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Institution.INSTITUTION.STATEMENT_EXPORT_PARAMS_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Institution.INSTITUTION.STATEMENT_IMPORT_FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return Institution.INSTITUTION.DISABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Institution.INSTITUTION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Institution.INSTITUTION.STATEMENT_API_EXPORTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEntityVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInstitutionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPaymentMethods();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getIsPrimary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getStatementExportFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getStatementExportParamsJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getStatementImportFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getStatementApiExporter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value4(Long value) {
        setEntityVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value7(String value) {
        setInstitutionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value8(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value9(String value) {
        setPaymentMethods(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value10(Boolean value) {
        setIsPrimary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value11(String value) {
        setStatementExportFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value12(String value) {
        setStatementExportParamsJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value13(String value) {
        setStatementImportFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value14(Boolean value) {
        setDisabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value15(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value16(String value) {
        setStatementApiExporter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord values(Long value1, LocalDateTime value2, String value3, Long value4, LocalDateTime value5, String value6, String value7, String value8, String value9, Boolean value10, String value11, String value12, String value13, Boolean value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstitutionRecord
     */
    public InstitutionRecord() {
        super(Institution.INSTITUTION);
    }

    /**
     * Create a detached, initialised InstitutionRecord
     */
    public InstitutionRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, String institutionType, String name, String paymentMethods, Boolean isPrimary, String statementExportFormat, String statementExportParamsJson, String statementImportFormat, Boolean disabled, String code, String statementApiExporter) {
        super(Institution.INSTITUTION);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, institutionType);
        set(7, name);
        set(8, paymentMethods);
        set(9, isPrimary);
        set(10, statementExportFormat);
        set(11, statementExportParamsJson);
        set(12, statementImportFormat);
        set(13, disabled);
        set(14, code);
        set(15, statementApiExporter);
    }
}
