/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.activity;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activity extends SchemaImpl {

    private static final long serialVersionUID = -249508728;

    /**
     * The reference instance of <code>activity</code>
     */
    public static final Activity ACTIVITY = new Activity();

    /**
     * The table <code>activity.activity</code>.
     */
    public final fintech.bo.db.jooq.activity.tables.Activity ACTIVITY_ = fintech.bo.db.jooq.activity.tables.Activity.ACTIVITY_;

    /**
     * No further instances allowed
     */
    private Activity() {
        super("activity", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            fintech.bo.db.jooq.activity.tables.Activity.ACTIVITY_);
    }
}
