/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.affiliate;


import fintech.bo.db.jooq.affiliate.tables.AffiliateRequest;
import fintech.bo.db.jooq.affiliate.tables.Event;
import fintech.bo.db.jooq.affiliate.tables.Lead;
import fintech.bo.db.jooq.affiliate.tables.Partner;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Affiliate extends SchemaImpl {

    private static final long serialVersionUID = -1282234471;

    /**
     * The reference instance of <code>affiliate</code>
     */
    public static final Affiliate AFFILIATE = new Affiliate();

    /**
     * The table <code>affiliate.affiliate_request</code>.
     */
    public final AffiliateRequest AFFILIATE_REQUEST = fintech.bo.db.jooq.affiliate.tables.AffiliateRequest.AFFILIATE_REQUEST;

    /**
     * The table <code>affiliate.event</code>.
     */
    public final Event EVENT = fintech.bo.db.jooq.affiliate.tables.Event.EVENT;

    /**
     * The table <code>affiliate.lead</code>.
     */
    public final Lead LEAD = fintech.bo.db.jooq.affiliate.tables.Lead.LEAD;

    /**
     * The table <code>affiliate.partner</code>.
     */
    public final Partner PARTNER = fintech.bo.db.jooq.affiliate.tables.Partner.PARTNER;

    /**
     * No further instances allowed
     */
    private Affiliate() {
        super("affiliate", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AffiliateRequest.AFFILIATE_REQUEST,
            Event.EVENT,
            Lead.LEAD,
            Partner.PARTNER);
    }
}
