/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.marketing.tables.records;


import fintech.bo.db.jooq.marketing.tables.MarketingCampaign;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketingCampaignRecord extends UpdatableRecordImpl<MarketingCampaignRecord> {

    private static final long serialVersionUID = -175586831;

    /**
     * Setter for <code>marketing.marketing_campaign.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.entity_version</code>.
     */
    public void setEntityVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.entity_version</code>.
     */
    public Long getEntityVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.main_marketing_template_id</code>.
     */
    public void setMainMarketingTemplateId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.main_marketing_template_id</code>.
     */
    public Long getMainMarketingTemplateId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.remind_marketing_template_id</code>.
     */
    public void setRemindMarketingTemplateId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.remind_marketing_template_id</code>.
     */
    public Long getRemindMarketingTemplateId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.name</code>.
     */
    public void setName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.name</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.email_subject</code>.
     */
    public void setEmailSubject(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.email_subject</code>.
     */
    public String getEmailSubject() {
        return (String) get(9);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.email_body</code>.
     */
    public void setEmailBody(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.email_body</code>.
     */
    public String getEmailBody() {
        return (String) get(10);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.sms</code>.
     */
    public void setSms(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.sms</code>.
     */
    public String getSms() {
        return (String) get(11);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.remind_email_subject</code>.
     */
    public void setRemindEmailSubject(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.remind_email_subject</code>.
     */
    public String getRemindEmailSubject() {
        return (String) get(12);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.remind_email_body</code>.
     */
    public void setRemindEmailBody(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.remind_email_body</code>.
     */
    public String getRemindEmailBody() {
        return (String) get(13);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.schedule_type</code>.
     */
    public void setScheduleType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.schedule_type</code>.
     */
    public String getScheduleType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.remind_interval_hours</code>.
     */
    public void setRemindIntervalHours(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.remind_interval_hours</code>.
     */
    public Integer getRemindIntervalHours() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.audience_settings_json_config</code>.
     */
    public void setAudienceSettingsJsonConfig(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.audience_settings_json_config</code>.
     */
    public String getAudienceSettingsJsonConfig() {
        return (String) get(16);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.main_promo_code_id</code>.
     */
    public void setMainPromoCodeId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.main_promo_code_id</code>.
     */
    public Long getMainPromoCodeId() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.remind_promo_code_id</code>.
     */
    public void setRemindPromoCodeId(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.remind_promo_code_id</code>.
     */
    public Long getRemindPromoCodeId() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.status</code>.
     */
    public void setStatus(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.status</code>.
     */
    public String getStatus() {
        return (String) get(19);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.main_image_file_id</code>.
     */
    public void setMainImageFileId(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.main_image_file_id</code>.
     */
    public Long getMainImageFileId() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.remind_image_file_id</code>.
     */
    public void setRemindImageFileId(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.remind_image_file_id</code>.
     */
    public Long getRemindImageFileId() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.has_main_promo_code</code>.
     */
    public void setHasMainPromoCode(Boolean value) {
        set(22, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.has_main_promo_code</code>.
     */
    public Boolean getHasMainPromoCode() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.has_remind_promo_code</code>.
     */
    public void setHasRemindPromoCode(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.has_remind_promo_code</code>.
     */
    public Boolean getHasRemindPromoCode() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.enable_remind</code>.
     */
    public void setEnableRemind(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.enable_remind</code>.
     */
    public Boolean getEnableRemind() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>marketing.marketing_campaign.schedule_date</code>.
     */
    public void setScheduleDate(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>marketing.marketing_campaign.schedule_date</code>.
     */
    public LocalDateTime getScheduleDate() {
        return (LocalDateTime) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarketingCampaignRecord
     */
    public MarketingCampaignRecord() {
        super(MarketingCampaign.MARKETING_CAMPAIGN);
    }

    /**
     * Create a detached, initialised MarketingCampaignRecord
     */
    public MarketingCampaignRecord(Long id, LocalDateTime createdAt, String createdBy, Long entityVersion, LocalDateTime updatedAt, String updatedBy, Long mainMarketingTemplateId, Long remindMarketingTemplateId, String name, String emailSubject, String emailBody, String sms, String remindEmailSubject, String remindEmailBody, String scheduleType, Integer remindIntervalHours, String audienceSettingsJsonConfig, Long mainPromoCodeId, Long remindPromoCodeId, String status, Long mainImageFileId, Long remindImageFileId, Boolean hasMainPromoCode, Boolean hasRemindPromoCode, Boolean enableRemind, LocalDateTime scheduleDate) {
        super(MarketingCampaign.MARKETING_CAMPAIGN);

        set(0, id);
        set(1, createdAt);
        set(2, createdBy);
        set(3, entityVersion);
        set(4, updatedAt);
        set(5, updatedBy);
        set(6, mainMarketingTemplateId);
        set(7, remindMarketingTemplateId);
        set(8, name);
        set(9, emailSubject);
        set(10, emailBody);
        set(11, sms);
        set(12, remindEmailSubject);
        set(13, remindEmailBody);
        set(14, scheduleType);
        set(15, remindIntervalHours);
        set(16, audienceSettingsJsonConfig);
        set(17, mainPromoCodeId);
        set(18, remindPromoCodeId);
        set(19, status);
        set(20, mainImageFileId);
        set(21, remindImageFileId);
        set(22, hasMainPromoCode);
        set(23, hasRemindPromoCode);
        set(24, enableRemind);
        set(25, scheduleDate);
    }
}
