/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.crm;


import fintech.bo.db.jooq.crm.tables.*;
import fintech.bo.db.jooq.crm.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>crm</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CountryRecord, Long> IDENTITY_COUNTRY = Identities0.IDENTITY_COUNTRY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClientRecord> CLIENT_PKEY = UniqueKeys0.CLIENT_PKEY;
    public static final UniqueKey<ClientRecord> UK_ND3IV3VIWO4NL1N6WQ5WSJAFQ = UniqueKeys0.UK_ND3IV3VIWO4NL1N6WQ5WSJAFQ;
    public static final UniqueKey<ClientAddressRecord> CLIENT_ADDRESS_PKEY = UniqueKeys0.CLIENT_ADDRESS_PKEY;
    public static final UniqueKey<ClientAttachmentRecord> CLIENT_ATTACHMENT_PKEY = UniqueKeys0.CLIENT_ATTACHMENT_PKEY;
    public static final UniqueKey<ClientAttributeRecord> CLIENT_ATTRIBUTE_PKEY = UniqueKeys0.CLIENT_ATTRIBUTE_PKEY;
    public static final UniqueKey<ClientBankAccountRecord> CLIENT_BANK_ACCOUNT_PKEY = UniqueKeys0.CLIENT_BANK_ACCOUNT_PKEY;
    public static final UniqueKey<ClientSegmentRecord> CLIENT_SEGMENT_PKEY = UniqueKeys0.CLIENT_SEGMENT_PKEY;
    public static final UniqueKey<CountryRecord> COUNTRY_PKEY = UniqueKeys0.COUNTRY_PKEY;
    public static final UniqueKey<EmailContactRecord> EMAIL_CONTACT_PKEY = UniqueKeys0.EMAIL_CONTACT_PKEY;
    public static final UniqueKey<EmailLoginRecord> EMAIL_LOGIN_PKEY = UniqueKeys0.EMAIL_LOGIN_PKEY;
    public static final UniqueKey<EmailLoginRecord> UK_8NIP4EQCKVXU35AB09A8CI3EF = UniqueKeys0.UK_8NIP4EQCKVXU35AB09A8CI3EF;
    public static final UniqueKey<EmailLoginRecord> IDX_EMAIL_LOGIN_CLIENT_ID = UniqueKeys0.IDX_EMAIL_LOGIN_CLIENT_ID;
    public static final UniqueKey<IdentityDocumentRecord> IDENTITY_DOCUMENT_PKEY = UniqueKeys0.IDENTITY_DOCUMENT_PKEY;
    public static final UniqueKey<PhoneContactRecord> PHONE_CONTACT_PKEY = UniqueKeys0.PHONE_CONTACT_PKEY;
    public static final UniqueKey<PhoneVerificationRecord> PHONE_VERIFICATION_PKEY = UniqueKeys0.PHONE_VERIFICATION_PKEY;
    public static final UniqueKey<ResetPasswordTokenRecord> RESET_PASSWORD_TOKEN_PKEY = UniqueKeys0.RESET_PASSWORD_TOKEN_PKEY;
    public static final UniqueKey<ResetPasswordTokenRecord> UK_M1Q62SO82ATXNTBPU9NRWU9O0 = UniqueKeys0.UK_M1Q62SO82ATXNTBPU9NRWU9O0;
    public static final UniqueKey<VerifyEmailTokenRecord> VERIFY_EMAIL_TOKEN_PKEY = UniqueKeys0.VERIFY_EMAIL_TOKEN_PKEY;
    public static final UniqueKey<VerifyEmailTokenRecord> UK_FNJ2PBPGSYMH6J0TQ0VQ3Q69V = UniqueKeys0.UK_FNJ2PBPGSYMH6J0TQ0VQ3Q69V;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClientAddressRecord, ClientRecord> CLIENT_ADDRESS__FK_CLIENT_ADDRESS_CLIENT_ID = ForeignKeys0.CLIENT_ADDRESS__FK_CLIENT_ADDRESS_CLIENT_ID;
    public static final ForeignKey<ClientAttachmentRecord, ClientRecord> CLIENT_ATTACHMENT__FK_CLIENT_ATTACHMENT_CLIENT_ID = ForeignKeys0.CLIENT_ATTACHMENT__FK_CLIENT_ATTACHMENT_CLIENT_ID;
    public static final ForeignKey<ClientAttributeRecord, ClientRecord> CLIENT_ATTRIBUTE__FK_CLIENT_ATTRIBUTE_CLIENT_ID = ForeignKeys0.CLIENT_ATTRIBUTE__FK_CLIENT_ATTRIBUTE_CLIENT_ID;
    public static final ForeignKey<ClientBankAccountRecord, ClientRecord> CLIENT_BANK_ACCOUNT__FK_CLIENT_BANK_ACCOUNT_CLIENT_ID = ForeignKeys0.CLIENT_BANK_ACCOUNT__FK_CLIENT_BANK_ACCOUNT_CLIENT_ID;
    public static final ForeignKey<ClientSegmentRecord, ClientRecord> CLIENT_SEGMENT__FK_CLIENT_SEGMENT_CLIENT_ID = ForeignKeys0.CLIENT_SEGMENT__FK_CLIENT_SEGMENT_CLIENT_ID;
    public static final ForeignKey<EmailContactRecord, ClientRecord> EMAIL_CONTACT__FK_EMAIL_CONTACT_CLIENT_ID = ForeignKeys0.EMAIL_CONTACT__FK_EMAIL_CONTACT_CLIENT_ID;
    public static final ForeignKey<EmailLoginRecord, ClientRecord> EMAIL_LOGIN__FK_EMAIL_LOGIN_CLIENT_ID = ForeignKeys0.EMAIL_LOGIN__FK_EMAIL_LOGIN_CLIENT_ID;
    public static final ForeignKey<IdentityDocumentRecord, ClientRecord> IDENTITY_DOCUMENT__FK_IDENTITY_DOCUMENT_CLIENT_ID = ForeignKeys0.IDENTITY_DOCUMENT__FK_IDENTITY_DOCUMENT_CLIENT_ID;
    public static final ForeignKey<IdentityDocumentRecord, CountryRecord> IDENTITY_DOCUMENT__FK_IDENTITY_DOCUMENT_NATIONALITY = ForeignKeys0.IDENTITY_DOCUMENT__FK_IDENTITY_DOCUMENT_NATIONALITY;
    public static final ForeignKey<PhoneContactRecord, ClientRecord> PHONE_CONTACT__FK_PHONE_CONTACT_CLIENT_ID = ForeignKeys0.PHONE_CONTACT__FK_PHONE_CONTACT_CLIENT_ID;
    public static final ForeignKey<PhoneVerificationRecord, ClientRecord> PHONE_VERIFICATION__FK_PHONE_VERIFICATION_CLIENT_ID = ForeignKeys0.PHONE_VERIFICATION__FK_PHONE_VERIFICATION_CLIENT_ID;
    public static final ForeignKey<PhoneVerificationRecord, PhoneContactRecord> PHONE_VERIFICATION__FK_PHONE_VERIFICATION_PHONE_CONTACT_ID = ForeignKeys0.PHONE_VERIFICATION__FK_PHONE_VERIFICATION_PHONE_CONTACT_ID;
    public static final ForeignKey<ResetPasswordTokenRecord, ClientRecord> RESET_PASSWORD_TOKEN__FK_RESET_PASSWORD_TOKEN_CLIENT_ID = ForeignKeys0.RESET_PASSWORD_TOKEN__FK_RESET_PASSWORD_TOKEN_CLIENT_ID;
    public static final ForeignKey<VerifyEmailTokenRecord, ClientRecord> VERIFY_EMAIL_TOKEN__FK_VERIFY_EMAIL_TOKEN_CLIENT_ID = ForeignKeys0.VERIFY_EMAIL_TOKEN__FK_VERIFY_EMAIL_TOKEN_CLIENT_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CountryRecord, Long> IDENTITY_COUNTRY = createIdentity(Country.COUNTRY, Country.COUNTRY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ClientRecord> CLIENT_PKEY = createUniqueKey(Client.CLIENT, "client_pkey", Client.CLIENT.ID);
        public static final UniqueKey<ClientRecord> UK_ND3IV3VIWO4NL1N6WQ5WSJAFQ = createUniqueKey(Client.CLIENT, "uk_nd3iv3viwo4nl1n6wq5wsjafq", Client.CLIENT.CLIENT_NUMBER);
        public static final UniqueKey<ClientAddressRecord> CLIENT_ADDRESS_PKEY = createUniqueKey(ClientAddress.CLIENT_ADDRESS, "client_address_pkey", ClientAddress.CLIENT_ADDRESS.ID);
        public static final UniqueKey<ClientAttachmentRecord> CLIENT_ATTACHMENT_PKEY = createUniqueKey(ClientAttachment.CLIENT_ATTACHMENT, "client_attachment_pkey", ClientAttachment.CLIENT_ATTACHMENT.ID);
        public static final UniqueKey<ClientAttributeRecord> CLIENT_ATTRIBUTE_PKEY = createUniqueKey(ClientAttribute.CLIENT_ATTRIBUTE, "client_attribute_pkey", ClientAttribute.CLIENT_ATTRIBUTE.CLIENT_ID, ClientAttribute.CLIENT_ATTRIBUTE.KEY);
        public static final UniqueKey<ClientBankAccountRecord> CLIENT_BANK_ACCOUNT_PKEY = createUniqueKey(ClientBankAccount.CLIENT_BANK_ACCOUNT, "client_bank_account_pkey", ClientBankAccount.CLIENT_BANK_ACCOUNT.ID);
        public static final UniqueKey<ClientSegmentRecord> CLIENT_SEGMENT_PKEY = createUniqueKey(ClientSegment.CLIENT_SEGMENT, "client_segment_pkey", ClientSegment.CLIENT_SEGMENT.CLIENT_ID, ClientSegment.CLIENT_SEGMENT.ADDED_AT, ClientSegment.CLIENT_SEGMENT.SEGMENT);
        public static final UniqueKey<CountryRecord> COUNTRY_PKEY = createUniqueKey(Country.COUNTRY, "country_pkey", Country.COUNTRY.ID);
        public static final UniqueKey<EmailContactRecord> EMAIL_CONTACT_PKEY = createUniqueKey(EmailContact.EMAIL_CONTACT, "email_contact_pkey", EmailContact.EMAIL_CONTACT.ID);
        public static final UniqueKey<EmailLoginRecord> EMAIL_LOGIN_PKEY = createUniqueKey(EmailLogin.EMAIL_LOGIN, "email_login_pkey", EmailLogin.EMAIL_LOGIN.ID);
        public static final UniqueKey<EmailLoginRecord> UK_8NIP4EQCKVXU35AB09A8CI3EF = createUniqueKey(EmailLogin.EMAIL_LOGIN, "uk_8nip4eqckvxu35ab09a8ci3ef", EmailLogin.EMAIL_LOGIN.EMAIL);
        public static final UniqueKey<EmailLoginRecord> IDX_EMAIL_LOGIN_CLIENT_ID = createUniqueKey(EmailLogin.EMAIL_LOGIN, "idx_email_login_client_id", EmailLogin.EMAIL_LOGIN.CLIENT_ID);
        public static final UniqueKey<IdentityDocumentRecord> IDENTITY_DOCUMENT_PKEY = createUniqueKey(IdentityDocument.IDENTITY_DOCUMENT, "identity_document_pkey", IdentityDocument.IDENTITY_DOCUMENT.ID);
        public static final UniqueKey<PhoneContactRecord> PHONE_CONTACT_PKEY = createUniqueKey(PhoneContact.PHONE_CONTACT, "phone_contact_pkey", PhoneContact.PHONE_CONTACT.ID);
        public static final UniqueKey<PhoneVerificationRecord> PHONE_VERIFICATION_PKEY = createUniqueKey(PhoneVerification.PHONE_VERIFICATION, "phone_verification_pkey", PhoneVerification.PHONE_VERIFICATION.ID);
        public static final UniqueKey<ResetPasswordTokenRecord> RESET_PASSWORD_TOKEN_PKEY = createUniqueKey(ResetPasswordToken.RESET_PASSWORD_TOKEN, "reset_password_token_pkey", ResetPasswordToken.RESET_PASSWORD_TOKEN.ID);
        public static final UniqueKey<ResetPasswordTokenRecord> UK_M1Q62SO82ATXNTBPU9NRWU9O0 = createUniqueKey(ResetPasswordToken.RESET_PASSWORD_TOKEN, "uk_m1q62so82atxntbpu9nrwu9o0", ResetPasswordToken.RESET_PASSWORD_TOKEN.TOKEN);
        public static final UniqueKey<VerifyEmailTokenRecord> VERIFY_EMAIL_TOKEN_PKEY = createUniqueKey(VerifyEmailToken.VERIFY_EMAIL_TOKEN, "verify_email_token_pkey", VerifyEmailToken.VERIFY_EMAIL_TOKEN.ID);
        public static final UniqueKey<VerifyEmailTokenRecord> UK_FNJ2PBPGSYMH6J0TQ0VQ3Q69V = createUniqueKey(VerifyEmailToken.VERIFY_EMAIL_TOKEN, "uk_fnj2pbpgsymh6j0tq0vq3q69v", VerifyEmailToken.VERIFY_EMAIL_TOKEN.TOKEN);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ClientAddressRecord, ClientRecord> CLIENT_ADDRESS__FK_CLIENT_ADDRESS_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, ClientAddress.CLIENT_ADDRESS, "client_address__fk_client_address_client_id", ClientAddress.CLIENT_ADDRESS.CLIENT_ID);
        public static final ForeignKey<ClientAttachmentRecord, ClientRecord> CLIENT_ATTACHMENT__FK_CLIENT_ATTACHMENT_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, ClientAttachment.CLIENT_ATTACHMENT, "client_attachment__fk_client_attachment_client_id", ClientAttachment.CLIENT_ATTACHMENT.CLIENT_ID);
        public static final ForeignKey<ClientAttributeRecord, ClientRecord> CLIENT_ATTRIBUTE__FK_CLIENT_ATTRIBUTE_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, ClientAttribute.CLIENT_ATTRIBUTE, "client_attribute__fk_client_attribute_client_id", ClientAttribute.CLIENT_ATTRIBUTE.CLIENT_ID);
        public static final ForeignKey<ClientBankAccountRecord, ClientRecord> CLIENT_BANK_ACCOUNT__FK_CLIENT_BANK_ACCOUNT_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, ClientBankAccount.CLIENT_BANK_ACCOUNT, "client_bank_account__fk_client_bank_account_client_id", ClientBankAccount.CLIENT_BANK_ACCOUNT.CLIENT_ID);
        public static final ForeignKey<ClientSegmentRecord, ClientRecord> CLIENT_SEGMENT__FK_CLIENT_SEGMENT_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, ClientSegment.CLIENT_SEGMENT, "client_segment__fk_client_segment_client_id", ClientSegment.CLIENT_SEGMENT.CLIENT_ID);
        public static final ForeignKey<EmailContactRecord, ClientRecord> EMAIL_CONTACT__FK_EMAIL_CONTACT_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, EmailContact.EMAIL_CONTACT, "email_contact__fk_email_contact_client_id", EmailContact.EMAIL_CONTACT.CLIENT_ID);
        public static final ForeignKey<EmailLoginRecord, ClientRecord> EMAIL_LOGIN__FK_EMAIL_LOGIN_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, EmailLogin.EMAIL_LOGIN, "email_login__fk_email_login_client_id", EmailLogin.EMAIL_LOGIN.CLIENT_ID);
        public static final ForeignKey<IdentityDocumentRecord, ClientRecord> IDENTITY_DOCUMENT__FK_IDENTITY_DOCUMENT_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, IdentityDocument.IDENTITY_DOCUMENT, "identity_document__fk_identity_document_client_id", IdentityDocument.IDENTITY_DOCUMENT.CLIENT_ID);
        public static final ForeignKey<IdentityDocumentRecord, CountryRecord> IDENTITY_DOCUMENT__FK_IDENTITY_DOCUMENT_NATIONALITY = createForeignKey(fintech.bo.db.jooq.crm.Keys.COUNTRY_PKEY, IdentityDocument.IDENTITY_DOCUMENT, "identity_document__fk_identity_document_nationality", IdentityDocument.IDENTITY_DOCUMENT.NATIONALITY_ID);
        public static final ForeignKey<PhoneContactRecord, ClientRecord> PHONE_CONTACT__FK_PHONE_CONTACT_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, PhoneContact.PHONE_CONTACT, "phone_contact__fk_phone_contact_client_id", PhoneContact.PHONE_CONTACT.CLIENT_ID);
        public static final ForeignKey<PhoneVerificationRecord, ClientRecord> PHONE_VERIFICATION__FK_PHONE_VERIFICATION_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, PhoneVerification.PHONE_VERIFICATION, "phone_verification__fk_phone_verification_client_id", PhoneVerification.PHONE_VERIFICATION.CLIENT_ID);
        public static final ForeignKey<PhoneVerificationRecord, PhoneContactRecord> PHONE_VERIFICATION__FK_PHONE_VERIFICATION_PHONE_CONTACT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.PHONE_CONTACT_PKEY, PhoneVerification.PHONE_VERIFICATION, "phone_verification__fk_phone_verification_phone_contact_id", PhoneVerification.PHONE_VERIFICATION.PHONE_CONTACT_ID);
        public static final ForeignKey<ResetPasswordTokenRecord, ClientRecord> RESET_PASSWORD_TOKEN__FK_RESET_PASSWORD_TOKEN_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, ResetPasswordToken.RESET_PASSWORD_TOKEN, "reset_password_token__fk_reset_password_token_client_id", ResetPasswordToken.RESET_PASSWORD_TOKEN.CLIENT_ID);
        public static final ForeignKey<VerifyEmailTokenRecord, ClientRecord> VERIFY_EMAIL_TOKEN__FK_VERIFY_EMAIL_TOKEN_CLIENT_ID = createForeignKey(fintech.bo.db.jooq.crm.Keys.CLIENT_PKEY, VerifyEmailToken.VERIFY_EMAIL_TOKEN, "verify_email_token__fk_verify_email_token_client_id", VerifyEmailToken.VERIFY_EMAIL_TOKEN.CLIENT_ID);
    }
}
