/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.crm;


import fintech.bo.db.jooq.crm.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in crm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crm.client</code>.
     */
    public static final Client CLIENT = fintech.bo.db.jooq.crm.tables.Client.CLIENT;

    /**
     * The table <code>crm.client_address</code>.
     */
    public static final ClientAddress CLIENT_ADDRESS = fintech.bo.db.jooq.crm.tables.ClientAddress.CLIENT_ADDRESS;

    /**
     * The table <code>crm.client_attachment</code>.
     */
    public static final ClientAttachment CLIENT_ATTACHMENT = fintech.bo.db.jooq.crm.tables.ClientAttachment.CLIENT_ATTACHMENT;

    /**
     * The table <code>crm.client_attribute</code>.
     */
    public static final ClientAttribute CLIENT_ATTRIBUTE = fintech.bo.db.jooq.crm.tables.ClientAttribute.CLIENT_ATTRIBUTE;

    /**
     * The table <code>crm.client_bank_account</code>.
     */
    public static final ClientBankAccount CLIENT_BANK_ACCOUNT = fintech.bo.db.jooq.crm.tables.ClientBankAccount.CLIENT_BANK_ACCOUNT;

    /**
     * The table <code>crm.client_segment</code>.
     */
    public static final ClientSegment CLIENT_SEGMENT = fintech.bo.db.jooq.crm.tables.ClientSegment.CLIENT_SEGMENT;

    /**
     * The table <code>crm.country</code>.
     */
    public static final Country COUNTRY = fintech.bo.db.jooq.crm.tables.Country.COUNTRY;

    /**
     * The table <code>crm.email_contact</code>.
     */
    public static final EmailContact EMAIL_CONTACT = fintech.bo.db.jooq.crm.tables.EmailContact.EMAIL_CONTACT;

    /**
     * The table <code>crm.email_login</code>.
     */
    public static final EmailLogin EMAIL_LOGIN = fintech.bo.db.jooq.crm.tables.EmailLogin.EMAIL_LOGIN;

    /**
     * The table <code>crm.identity_document</code>.
     */
    public static final IdentityDocument IDENTITY_DOCUMENT = fintech.bo.db.jooq.crm.tables.IdentityDocument.IDENTITY_DOCUMENT;

    /**
     * The table <code>crm.marketing_consent_log</code>.
     */
    public static final MarketingConsentLog MARKETING_CONSENT_LOG = fintech.bo.db.jooq.crm.tables.MarketingConsentLog.MARKETING_CONSENT_LOG;

    /**
     * The table <code>crm.phone_contact</code>.
     */
    public static final PhoneContact PHONE_CONTACT = fintech.bo.db.jooq.crm.tables.PhoneContact.PHONE_CONTACT;

    /**
     * The table <code>crm.phone_verification</code>.
     */
    public static final PhoneVerification PHONE_VERIFICATION = fintech.bo.db.jooq.crm.tables.PhoneVerification.PHONE_VERIFICATION;

    /**
     * The table <code>crm.reset_password_token</code>.
     */
    public static final ResetPasswordToken RESET_PASSWORD_TOKEN = fintech.bo.db.jooq.crm.tables.ResetPasswordToken.RESET_PASSWORD_TOKEN;

    /**
     * The table <code>crm.verify_email_token</code>.
     */
    public static final VerifyEmailToken VERIFY_EMAIL_TOKEN = fintech.bo.db.jooq.crm.tables.VerifyEmailToken.VERIFY_EMAIL_TOKEN;
}
