package fintech.spain.experian.impl.concursales;

public enum ExperianConcursalesRequestParameter  {

	ID_SUBSCRIBER("ID_SUSCRIPTOR"),
	REFERENCE_CONSULTATION("REFERENCIA_CONSULTA"),
	DATE("FECHA"),
	CREDITORS_CONTEST_WITHOUT_LIQUIDATION_REQUEST("CONCURSO_ACREEDORES_SIN_PETICION_LIQUIDACION"),
	CREDITORS_CONTEST_WITH_LIQUIDATION_REQUEST("CONCURSO_ACREEDORES_CON_PETICION_LIQUIDACION"),
	CREDITORS_CONTEST_WITHOUT_BREACH("CONVENIO_ACREEDORES_SIN_INCUMPLIMIENTO"),
	CREDITORS_CONTEST_WITH_BREACH("CONVENIO_ACREEDORES_CON_INCUMPLIMIENTO"),
	LIQUIDATION("LIQUIDACION"),
	SITUATION_NORMAL("SITUACION_NORMAL"),
	RETURN_RECORDS_FROM_INDEX("NUMERO_ORDEN"),
	RETURN_RECORDS_COUNT("NUMERO_REGISTROS");

	private final String key;

    ExperianConcursalesRequestParameter(final String key) {
		this.key = key;
	}

	public String getKey() {
		return key;
	}
}
