/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.security;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in security
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>security.permission_id_seq</code>
     */
    public static final Sequence<Long> PERMISSION_ID_SEQ = new SequenceImpl<Long>("permission_id_seq", Security.SECURITY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>security.role_id_seq</code>
     */
    public static final Sequence<Long> ROLE_ID_SEQ = new SequenceImpl<Long>("role_id_seq", Security.SECURITY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>security.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Security.SECURITY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
