/*
 * This file is generated by jOOQ.
*/
package fintech.bo.db.jooq.cms;


import fintech.bo.db.jooq.cms.tables.Item;
import fintech.bo.db.jooq.cms.tables.Locale;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cms
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cms.item</code>.
     */
    public static final Item ITEM = fintech.bo.db.jooq.cms.tables.Item.ITEM;

    /**
     * The table <code>cms.locale</code>.
     */
    public static final Locale LOCALE = fintech.bo.db.jooq.cms.tables.Locale.LOCALE;
}
